### ISSUE TITLE
Add credo for linting/style checking

### ISSUE THREAD

**Issue by bjhaid** [kafkaex/kafka_ex#100]
Credo can be found at:

https://github.com/rrrene/credo

Whoever takes this should ensure all credo warnings/errors are cleaned up

**Comment by dantswain** [comment]
```
Analysis took 1.8 seconds (0.02s to load, 1.8s running checks)
132 mods/funs, found 51 consistency issues, 10 warnings, 22 refactoring opportunities, 30 code readability issues, 7 software design suggestions.
```

:scream:

**Comment by dantswain** [comment]
I have a feeling this is going to touch a lot of lines of code, so I'm wondering if it would make sense to break it up and attack bits and pieces as time allows?
