### ISSUE TITLE
Support TLS?

### ISSUE THREAD

**Issue by fire** [kafkaex/kafka_ex#120]
Does this library support TLS in kafka?

**Comment by bjhaid** [comment]
Not yet, we plan to support it sometimes soon

**Comment by fire** [comment]
Great!

**Comment by ghbutton** [comment]
Heroku only supports Kafka is we have ssl

**Comment by bjhaid** [comment]
@ghbutton I don't understand what you mean by:

> Heroku only supports Kafka is we have ssl

**Comment by ghbutton** [comment]
Sorry, what I mean is heroku supports a managed kafka cluster, but ssl is required to connect with it.

```
Heroku Kafka supports SSL to encrypt and authenticate all connections. Because of this, you must use a library which supports SSL encryption and client certificates.
```

**Comment by ook** [comment]
#146  ;)

**Comment by ghbutton** [comment]
Awesome thanks

**Comment by ook** [comment]
Tested with success against Heroku Kafka, works great. A big thank you. 👍

**Comment by bjhaid** [comment]
As stated by @ook this is done in #146 and all our integration test uses ssl by default now, I will push a new release sometimes this weekend
