### ISSUE TITLE
Failing test for disable_default_worker

### ISSUE THREAD

**Issue by blackfist** [kafkaex/kafka_ex#123]
When you run `mix test --no-start` one of the tests fails.

```
  1) test Setting disable_default_worker to true removes the KafkaEx.Server worker (KafkaExTest)
     test/kafka_ex_test.exs:4
     ** (MatchError) no match of right hand side value: {:error, {:not_started, :kafka_ex}}
     stacktrace:
       test/kafka_ex_test.exs:6
```

The reason for the failing test is that the test tries to run `Application.stop(:kafka_ex)` but since we run `mix test` with `--no-start` there is no `:kafka_ex` application to stop. I talked to @bjhaid in the kafka_ex chat room and he's cool with moving that test in with the other integration tests.

I'll try to send a PR today.

**Comment by eproxus** [comment]
Another nice addition would be to alias `mix test` to `mix test --no-start`. :smile:

**Comment by bjhaid** [comment]
@eproxus 👍
