### ISSUE TITLE
Type spec inconsistency

### ISSUE THREAD

**Issue by eproxus** [kafkaex/kafka_ex#134]
I've noticed an inconsistency yielding some Dialyzer errors. In the `KafkaEx.Protocol.Producer.Request` struct, the `required_acks` field is specced as a `binary()` but initialized as an integer `0`: https://github.com/kafkaex/kafka_ex/blob/master/lib/kafka_ex/protocol/produce.ex#L15-L16

Not sure what the fix would be, therefore reporting this as an issue.

**Comment by bjhaid** [comment]
It should be an integer (0,1,2) the fix is to correct the spec, thanks for reporting this, I will fix sometimes today

**Comment by bjhaid** [comment]
err it's -1, 0,1 not (0,1,2) as stated

**Comment by eproxus** [comment]
Another question: Shouldn't the default be 1 or 2 instead of 0? It's more intuitive and stable to have acks on by default, I think.

**Comment by bjhaid** [comment]
Default is 0, if you really care about guarantees/consistency you should use 1, we probably should document this

**Comment by bjhaid** [comment]
actually this is documented

**Comment by eproxus** [comment]
I guess I'm just arguing that guarantees and consistency should be the default. :smile:
