### ISSUE TITLE
How to use KafkaEx with something like Poolboy?

### ISSUE THREAD

**Issue by JGulbronson** [kafkaex/kafka_ex#137]
I'm trying to use KafkaEx with Poolboy, using unnamed workers, but am struggling for the following reasons:

1. KafkaEx workers are managed by the KafkaEx Supervisor in a different app, which brings them up as they fail
2. There's no way (that I can see), where I can access those workers under the supervisor.

Because of this, whenever there are temporary Kafka issues, new processes are spawned, and the old ones are brought back up as well. This has accounted for over 3500 KafkaEx workers, essentially a memory leak in the app. 

Is there a recommended way to interact with something like Poolboy? I feel like this behaviour could be documented better in the docs.

**Comment by dantswain** [comment]
Hi @JGulbronson, thanks for the heads up!

I'm not super familiar with Poolboy, just the basic idea, and I'm not sure it makes sense to use Poolboy with Kafka.  E.g., connection pooling doesn't necessarily make sense because a Kafka client needs to maintain metadata state about the cluster and whatnot.  It's very possible that I'm misunderstanding, though.  Can you expand on how you're using Poolboy with KafkaEx, from a high-level perspective?

**Comment by JGulbronson** [comment]
Sure! Sorry, in retrospect my original comment didn't provide much context.

Currently, we have a pool of Publishers, managed by poolboy. When a Publisher starts, it creates an unnamed `KafkaEx.Worker`, which it uses for the actual publish to Kafka. This means that if a Publisher fails for whatever reason, it will be restarted by poolboy, and the `KafkaEx.Worker` it started will be restarted by the `KafkaEx.Supervisor`. Then, another worker will be started, because the Publisher's init method will be called again. As this happens, the number of workers continues to grow.

It seems that to fix this, the best option would be to provide a way for poolboy to manage the workers directly, as the current README says:

```
Create an unnamed KafkaEx worker

You may find you want to create many workers, say in conjunction with a poolboy pool. In this scenario you usually won't want to name these worker processes.
```

I'm still relatively new to Elixir though, so I might be misunderstanding the Elixir way of doing things. It seems a little non-obvious on how to use poolboy properly though, and I'd love to contribute back to the README with an example once my understanding improves!

**Comment by bjhaid** [comment]
As a follow up to what @dantswain said, if your app is consume heavy you should not be using poolboy, but for produce heavy apps you can make a case for poolboy. If you really want to use Poolboy you will need to call `GenServer.start_link(KafkaEx.Server, [[uris: Application.get_env(:kafka_ex, :brokers), consumer_group: Application.get_env(:kafka_ex, :consumer_group)], :no_name]` manually to create the worker and then pass it on to poolboy, this way it is not supervised by `KafkaEx.Supervisor`

**Comment by JGulbronson** [comment]
Yeah, we're entirely producing, no consumption.

That seems like what I needed though, I'll give it a shot and report back!

**Comment by JGulbronson** [comment]
`GenServer.start_link` should be fine. Worst case scenario is the worker brings down the linked process, and then poolboy brings them both back up.

Also, your suggestion of manually managing them works great! Do you think it's worth submitting a PR to update the README in the relevant section?

**Comment by bjhaid** [comment]
Closed with https://github.com/kafkaex/kafka_ex/issues/138

**Comment by thuey** [comment]
@bjhaid 
>if your app is consume heavy you should not be using poolboy, but for produce heavy apps you can make a case for poolboy

What should you do if your app _is_ consume heavy?

**Comment by dantswain** [comment]
@thuey The only real way to scale consumer speed with Kafka is to have more partitions.  The basic model of Kafka kind of necessitates one connection per partition.  You may be using poolboy for a worker pool on the client side, but that's outside the scope of KafkaEx.

I recommend pinging us on the #kafkaex channel on elixir-lang.slack.com for further advice.
