### ISSUE TITLE
Latest stable version 0.5.0 does not handle offsets correct with Kafka 0.9.0

### ISSUE THREAD

**Issue by lachezar** [kafkaex/kafka_ex#147]
I tried using the latest stable version 0.5.0 and Kafka 0.9.0 (kafka: stable 0.9.0.0 (bottled), HEAD), but every time when I restart the iex shell, the offset is reset to the very first message instead to the last non-consumed message.

Steps to reproduce it:
0. auto_commit is on
1. Add few messages to Kafka
2. Consume them `KafkaEx.fetch("test", 0)`
3. Kill and start iex again
4. Try `KafkaEx.fetch("test", 0)`
Result: You get all messages from the beginning of step 1

[Config file](https://gist.github.com/lachezar/e67c700b64d95714bdaa03d3148547c1)

The actual problem is not reproducible in the master branch.

I lost few hours debugging and scratching my head and I hope this ticket might safe other people's time.

**Comment by bjhaid** [comment]
@lachezar can you post the relevant portions of your `config.exs` and supply a small enough example to reproduce this

**Comment by lachezar** [comment]
Added config and steps. I am inexperienced with Kafka and Elixir (so there is a slim chance of me doing something wrong). I have tried it inside of a new Phoenix sample app with one GenServer.

**Comment by bjhaid** [comment]
Published [0.6.0](https://hex.pm/packages/kafka_ex/0.6.0)
