### ISSUE TITLE
New to kafka_ex: KafkaEx.latest_offset

### ISSUE THREAD

**Issue by jamsavvy** [kafkaex/kafka_ex#152]
Hello again,

I've tried getting the latest offset using KafkaEx.latest_offset but the value for offset is a character:

![latest_offset_error](https://cloud.githubusercontent.com/assets/23204231/20333202/f9a654a4-abeb-11e6-922e-99117a2062b8.PNG)

I used this code:
IO.puts "Earliest offset is: #{inspect KafkaEx.earliest_offset("jamtest", 0)}"
IO.puts "Latest offset is: #{inspect KafkaEx.latest_offset("jamtest", 0)}"

Am I using it correctly?

**Comment by cdegroot** [comment]
Could it be that the offset is actually 39 and Elixir/Erlang is trying to be helpful by representing this as an ASCII char?

**Comment by cdegroot** [comment]
(did some digging - Kafka V2 Offsets response indeed specifies a list of offsets, see https://kafka.apache.org/protocol. It's late so I can't find a reason why you would have a list of offsets there, but I'm sure they made it into a list for a reason. So it looks like the regular Elixir behavior:

```
iex(1)> [39]
'\''
```

**Comment by jamsavvy** [comment]
@cdegroot Thanks, now it makes sense!

**Comment by cdegroot** [comment]
You're welcome. And I couldn't help digging a bit further. https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-OffsetAPI(AKAListOffset) says:

> The response contains the starting offset of each segment for the requested partition as well as the "log end offset" i.e. the offset of the next message that would be appended to the given partition.
>
> We agree that this API is slightly funky.

So there you have it.

**Comment by jamsavvy** [comment]
Thanks to @cdegroot , I had forgotten about char lists :).
