### ISSUE TITLE
Run builds on CircleCI

### ISSUE THREAD

**Issue by bjhaid** [kafkaex/kafka_ex#153]
Given the recent flakiness of travis, we need to add a backup to Travis and the kafkaex slack room all suggest CirlceCI

**Comment by dantswain** [comment]
@bjhaid Do we still need this?  It doesn't seem like travis has been an issue lately.  Elixir is not officially supported on circle though with docker it shouldn't be _that_ hard to do.

**Comment by bjhaid** [comment]
I'll close this, we can revisit if travis ever goes flaky again
