### ISSUE TITLE
SyncGroup Request Serializes UserData at Top Level

### ISSUE THREAD

**Issue by dcuddeback** [kafkaex/kafka_ex#161]
In [`SyncGroupRequest`](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-SyncGroupRequest), `UserData` is shown as the last field of `MemberAssignment`, but it's currently serialized once at the end of the `SyncGroupRequest`.

**Comment by cdegroot** [comment]
That thing is a bit funny in that `UserData` is there, but `MemberAssignment` doesn't specify where it actually falls

```
MemberAssignment => Version PartitionAssignment
  Version => int16
  PartitionAssignment => [Topic [Partition]]
    Topic => string
    Partition => int32
  UserData => bytes
```

If `UserData` would be used, I'd say the first line would include it. I'll need to dive into the Java client library to figure this out, unless someone has a simple STR (note: this is not really part of the Kafka protocol proper - it's part of how the Java library interprets the `MemberAssignment` bytes for `SyncGroupRequest`; it's our choice whether we want to be compatible or not, although I'd be hard-pressed to come up with a sensible reason for a mixed Elixir/Java consumer cluster running as a single consumer group).

**Comment by dcuddeback** [comment]
@cdegroot Where it's serialized right now, `UserData` is not inside `MemberAssignment`. Consider if `assignments` is an empty list [here](https://github.com/kafkaex/kafka_ex/blob/6e4b21b79fe08afb682dbb7769e4bd2b47a48d27/lib/kafka_ex/protocol/sync_group.ex#L25), then user data (`0 :: 32-signed`) is still appended on the next line. That would correspond to adding a 32-bit 0 value at the end of `SyncGroupRequest` when `GroupAssignment` is a 0-length array:

```
SyncGroupRequest => GroupId GenerationId MemberId GroupAssignment
  GroupId => string
  GenerationId => int32
  MemberId => string
  GroupAssignment => [MemberId MemberAssignment]
    MemberId => string
    MemberAssignment => bytes
```

**Comment by cdegroot** [comment]
I've looked at the Java client, and the specification for member assignment should indeed be:

```
MemberAssignment => Version PartitionAssignment UserData
  Version => int16
  PartitionAssignment => [Topic [Partition]]
    Topic => string
    Partition => int32
  UserData => bytes
```

(see: https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerProtocol.java#L78) - so corresponding PR should be fine. Note that this is all pending a proper test with a mixed Java/kafka_ex consumer group, of course.
