### ISSUE TITLE
Add support for DeleteTopics API

### ISSUE THREAD

**Issue by bjhaid** [kafkaex/kafka_ex#169]
https://kafka.apache.org/protocol.html

**Comment by mbana** [comment]
+1

**Comment by jbruggem** [comment]
Implemented in Kafka 0.10.0.0: https://issues.apache.org/jira/browse/KAFKA-3307

**Comment by jbruggem** [comment]
Supported by Kafka since version 0.10.1.0 

See: https://issues.apache.org/jira/browse/KAFKA-2946

**Comment by jbruggem** [comment]
I think this can be closed.
