### ISSUE TITLE
Test with dockerized kafka/zookeeper

### ISSUE THREAD

**Issue by dantswain** [kafkaex/kafka_ex#170]
This will open the door to a few things:
* Testing against multiple versions of kafka
* Ensuring a clean slate for every run of the tests - maybe eventually get rid of the randomized topic names
* Maybe getting rid of the duplicate test runs

**Comment by dantswain** [comment]
This is partly done - as of #181 Travis is running the tests with docker, as of #182 the README is recommending testing with docker.

I'd still like to get testing of non-ssl and the other kafka version servers.

**Comment by joshuawscott** [comment]
@dantswain As far as I can tell this is done?

**Comment by Argonus** [comment]
We've it in docker already.
