### ISSUE TITLE
Documentation Bug?

### ISSUE THREAD

**Issue by philippneugebauer** [kafkaex/kafka_ex#189]
I tried to include kafka_ex to my application, but the only thing I receive is the following error:

```
** (exit) exited in: GenServer.call(KafkaEx.Supervisor, {:start_child, [[uris: [{"localhost", 9092}], consumer_group: :no_consumer_group, use_ssl: false, ssl_options: []], :kafka]}, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```

I was following pretty much following the Readme, I just needed to adapt the following to the new? elixir syntax:

```
  def application do
    # Specify extra applications you'll use from Erlang/Elixir
    [extra_applications: [:logger, :kafka_ex]]
  end
```

Thats my config:

```
use Mix.Config

config :kafka_ex,
  # a list of brokers to connect to in {"HOST", port} format
  brokers: [
    {"localhost", 9092}
  ],
  # the default consumer group for worker processes, must be a binary (string)
  #    NOTE if you are on Kafka < 0.8.2 or if you want to disable the use of
  #    consumer groups, set this to :no_consumer_group (this is the
  #    only exception to the requirement that this value be a binary)
  consumer_group: :no_consumer_group,
  # Set this value to true if you do not want the default
  # `KafkaEx.Server` worker to start during application start-up -
  # i.e., if you want to start your own set of named workers
  disable_default_worker: false,
  # Timeout value, in msec, for synchronous operations (e.g., network calls)
  sync_timeout: 3000,
  # Supervision max_restarts - the maximum amount of restarts allowed in a time frame
  max_restarts: 10,
  # Supervision max_seconds -  the time frame in which :max_restarts applies
  max_seconds: 60,
  # This is the flag that enables use of ssl
  use_ssl: false,
  # set this to the version of the kafka broker that you are using
  # include only major.minor.patch versions.  must be at least 0.8.0
  kafka_version: "10.1.1"

env_config = Path.expand("#{Mix.env}.exs", __DIR__)
if File.exists?(env_config) do
  import_config(env_config)
end
```

Did I miss any implicit change or what exactly do I wrong since the application seems to work well for everyone else? Just to mention, I was able to connect to `kafka` using `kafkacat` with `localhost:9092`

**Comment by dantswain** [comment]
Thanks for this info!  I haven't run into this before but that doesn't mean it's not a real issue. Are you starting a worker manually in your code during startup?

**Comment by philippneugebauer** [comment]
That's the way I'm starting the worker: I tried it this way via code and also terminal and I always receive the quoted error:
```
{:ok, _pid} = KafkaEx.create_worker(:kafka)
```

**Comment by bjhaid** [comment]
Can you remove `:kafka_ex` from `extra_applications` and report back your findings, I will also attempt to reproduce

**Comment by philippneugebauer** [comment]
Does not change anything

**Comment by joshuawscott** [comment]
Are you inlcuding `:kafka_ex` in your applications (not `:extra_applications`)?

**Comment by philippneugebauer** [comment]
First, my complete config:

```
defmodule Drones.Mixfile do
  use Mix.Project

  def project do
    [app: :drones,
     version: "0.1.0",
     elixir: "~> 1.4",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps()]
  end

  def application do
    # Specify extra applications you'll use from Erlang/Elixir
    [applications: [:kafka_ex]],
    [extra_applications: [:logger]]
  end

  defp deps do
    [
      {:credo, "~> 0.5", only: [:dev, :test]},
      {:dogma, "~> 0.1", only: [:dev, :test]},
      {:kafka_ex, "~> 0.6.3"}
    ]
  end
end
```

I also tried variations like:

```
  def application do
    # Specify extra applications you'll use from Erlang/Elixir
    [applications: [:kafka_ex],
    extra_applications: [:logger]]
  end
```

```
  def application do
    # Specify extra applications you'll use from Erlang/Elixir
    [applications: [:kafka_ex]]
  end
```

**Comment by bjhaid** [comment]
your config is missing `mod: {MyApp, []},` and you should not append `:kafka_ex` to the `extra_applications`, should be under `applications` instead

**Comment by joshuawscott** [comment]
I put together a repo that uses the config you provided: https://github.com/joshuawscott/kafkacat and it seems to work as expected.

**Comment by philippneugebauer** [comment]
I found the problem. I never expected it to be caused there:
`iex -S mix compile` => Does not work
`iex -S mix` => Works

Since I just started developing with Elixir, I have no clue what's the problem, but at least I resolved the problem now. Thanks a lot :)

**Comment by philippneugebauer** [comment]
Anyways, since Elixir's standard Mix config is now `[extra_applications: [:logger]]`, I guess you should follow that and update your Readme according to that to `[extra_applications: [:logger, :kafka_ex]] instead of the `mod: ..` stuff

**Comment by bjhaid** [comment]
@philippneugebauer we support elixir >= 1.1.0, which still requires the old syntax, given the old syntax is compatible with newer versions of elixir, I'll prefer we keep the docs same till we drop support for the older versions
