### ISSUE TITLE
stream/3 hangs

### ISSUE THREAD

**Issue by kevinbader** [kafkaex/kafka_ex#191]
Hi all,

I'm not sure whether I don't understand how stream/3 is supposed to work, or it's buggy:

```
defmodule KafkaTest do
  @moduledoc false
  @topic "elixirtest"
  @partition 0

  # this works
  def uses_stream_immediately_takes_two do
    KafkaEx.stream(@topic, @partition, offset: 0)
    |> Stream.map(& "the value: " <> &1.value)
    |> Enum.take(2)
  end

  # using to_list instead of take causes the method to never return:
  def uses_stream_immediately_takes_all do
    KafkaEx.stream(@topic, @partition, offset: 0)
    |> Stream.map(& "the value: " <> &1.value)
    |> Enum.to_list
  end

  # not using the stream immediately causes the method to never return, too:
  def waits_before_using_the_stream_takes_two do
    theStream = KafkaEx.stream(@topic, @partition, offset: 0)
    :timer.sleep(1000)  # waiting a bit..
    theStream
    |> Stream.map(& "the value: " <> &1.value)
    |> Enum.take(2)
  end
end
```

**Comment by dantswain** [comment]
I think this is a consequence of how `stream/3` currently works.  @bjhaid may have more info, but we have #185 to manage a rewrite.

**Comment by bjhaid** [comment]
It's due to the implementation of stream in kafka_ex, it uses GenEvent for streaming which we intend to replace in the issue @dantswain linked and I believe it's related to this: https://github.com/elixir-lang/elixir/issues/3138.

I have some WIP branch for #185 that I'll invest more time in this week to complete

**Comment by dantswain** [comment]
Hi @kevinbader The stream rewrite is complete.  If you have a chance could you check out the latest master and see if it still exhibits this behavior?

**Comment by dantswain** [comment]
I'm going to close this unless we get a confirmation that the problem persists after the stream rewrite.
