### ISSUE TITLE
Certificates from ENV instead of files?

### ISSUE THREAD

**Issue by Fuffi** [kafkaex/kafka_ex#194]
Is there any quick solution to get these? My idea was to create the files from ENV on app boot, but it's not ideal considering I'm hosting on Heroku

**Comment by dantswain** [comment]
That's a really great question.  We pass the ssl options directly to the erlang ssl module - http://erlang.org/doc/man/ssl.html - so if you can find a set of configurations that works for erlang ssl, it should work for KakaEx.  If you find something, would you mind sharing it back here so that others can see the solution?

**Comment by dantswain** [comment]
Ah I spoke too soon. It looks like we verify the ssl options and enforce that cacertfile, certfile, and keyfile are present.  This could be a strong case to remove those checks if you can get it to work with a different set of options.  You could bypass those checks by changing this line https://github.com/kafkaex/kafka_ex/blob/master/lib/kafka_ex/config.ex#L52 to just be `defp ssl_options(true, options), do options`.

**Comment by bjhaid** [comment]
ENV doesn't play nicely with releases so we might not support reading certificates from ENV, your idea should be the way to go. If it's security concerns that makes you think it's not ideal, then anyone who has access to read the disk can dump whatever they want from memory or iex/erl. You should just make sure you are cleaning up your certificates at shutdown.

I am also wondering what do people do with SSL and Phoenix in heroku, probably that will give us direction

**Comment by dantswain** [comment]
IMO we should support any combination of settings that works with the ssl module.  We don't do anything special with the certfile/etc settings except to verify that they exist and are readable files, which is something that was just done with the intention of helping people debug startup problems.  If there is a combination of settings that works and doesn't use those files (I'm not familiar enough with ssl to know the answer to that), then I think we should support it - the simplest way to do so would be to just get rid of those checks on the files.

**Comment by Fuffi** [comment]
@bjhaid not sure what problems you have with ENV, but Heroku's Kafka service gives you the certs via ENV variables so if you want to support Heroku I think you should consider lifting the enforcement of the cert files... Anyway I fixed it by creating the files in the /tmp folder on boot... Not ideal but it worked

**Comment by dantswain** [comment]
It looks like the `:cert`, `:key`, and `:cacerts` keys can be used to supply strings directly.  I think we should allow any valid configuration options.

**Comment by bjhaid** [comment]
@Fuffi I don't have problems with ENV, releases do, based on @dantswain comment we should just allow things that are valid to `:ssl` which I agree with

**Comment by Fuffi** [comment]
Hi, any updates on this?

**Comment by dantswain** [comment]
It should be possible to use the full set of ssl options as of 0.6.5
