### ISSUE TITLE
Offset option works oddly in stream/3

### ISSUE THREAD

**Issue by tzzzoz** [kafkaex/kafka_ex#208]
I have a topic named `requests`, then I produced only one message to this topic by this way:
`KafkaEx.produce("requests", 0, "hey")`
When I tried`KafkaEx.stream("requests", 0, offset:  0) |> Enum.to_list`, as the way I understand, it should return the message I produced, but it didn't. Instead it returned back `[]`, an empty list.

I followed [this example](https://hexdocs.pm/kafka_ex/KafkaEx.html#stream/3-example) as well. I expected to have the last message by passing `offset: 1` (since we have only 2 messages in this partition.), but when I did `KafkaEx.stream("foo", 0, offset: 1) |> Enum.to_list`, it returned also `[]`.

I found that when we pass the offset option where `offset = number_of_message - 1`, stream/3 will always return `[]`. I'm not sure if this is a normal behaviour, or it's buggy.

**Comment by dantswain** [comment]
Hi @tzzzoz can you retry your experiment with the current master?  The stream implementation has been rewritten and should behave correctly.

**Comment by tzzzoz** [comment]
Thanks for your great works! 👍  I just upgraded to `0.7.0` and it seems that it works very well. So, I will close this issue.

**Comment by dantswain** [comment]
:+1: Thanks for confirming, @tzzzoz !
