### ISSUE TITLE
ENV variables

### ISSUE THREAD

**Issue by retgoat** [kafkaex/kafka_ex#209]
Hey!

I'm trying to configure KafkaEx with env variables and [Envy](https://github.com/BlakeWilliams/envy)

But it seems KafkaEx trying to start before all variables are read.

Here is my config file

```elixir
config :kafka_ex,
  brokers: [
    {System.get_env("BROKER_HOST"), 9092}
  ],
  auto_commit: false,
  use_ssl: false,
  consumer_group: System.get_env("CONSUMER_GROUP")
```

Here is the error raised on app start

```
** (Mix) Could not start application kafka_ex: KafkaEx.start(:normal, []) returned an error: an exception was raised:
    ** (FunctionClauseError) no function clause matching in Regex.scan/3
        (elixir) lib/regex.ex:396: Regex.scan(~r/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/, nil, [])
        (kafka_ex) lib/kafka_ex/network_client.ex:56: KafkaEx.NetworkClient.format_host/1
        (kafka_ex) lib/kafka_ex/network_client.ex:9: KafkaEx.NetworkClient.create_socket/4
        (kafka_ex) lib/kafka_ex/server_0_p_9_p_0.ex:56: anonymous fn/3 in KafkaEx.Server0P9P0.kafka_server_init/1
        (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
        (kafka_ex) lib/kafka_ex/server_0_p_9_p_0.ex:56: KafkaEx.Server0P9P0.kafka_server_init/1
        (stdlib) gen_server.erl:328: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

If I set all config values without env vars all work perfectly.
Could you please advice?

Many thanks!

**Comment by retgoat** [comment]
Sorry, my bad. I should set `disable_default_worker: true` and then start my own.

**Comment by dantswain** [comment]
@retgoat Glad to see you were able to resolve this!  You may want to be careful about using `System.get_env/1` (or any other function calls) in your config.exs.  The config.exs file gets evaluated at compile time, not at run time.  It might not work as expected, depending on how you deploy & run your code.
