### ISSUE TITLE
Avro compression

### ISSUE THREAD

**Issue by jadbox** [kafkaex/kafka_ex#216]
Most modern use of Kafka is with Avro compression. Is this possible with this lib? If so, could we get an example?

**Comment by dantswain** [comment]
Hi!  I don't believe any client integration is required to send Avro messages over Kafka.  One would simply serialize their Avro messages before publishing and then deserialize on consume. The binary data should go over the wire just fine. 

The only compression codecs that Kafka supports are gzip, snappy, and LZ4. KafkaEx currently supports gzip and snappy.

I'm going to close this issue. Please feel free to visit the #kafkaex channel on the elixir-lang slack for questions!

**Comment by dplummer** [comment]
Hey @jadbox, I use Avro encoding of messages. We wrapped the Erlang `erlavro` library in Elixir with [Avrolixr](https://github.com/avvo/avrolixr). We haven't done a good job on docs for that project, but you should be able to add it to your deps `{:avrolixr, "~> 0.3"},` then decode the binary message with `Avrolixr.Codec.decode`.
