### ISSUE TITLE
There's no way to set fetch options for GenConsumer

### ISSUE THREAD

**Issue by dantswain** [kafkaex/kafka_ex#239]
max_bytes and min_bytes are important to some users.  We are also not passing a value for auto_commit, so probably actually committing messages before we mean to.

**Comment by adrienmo** [comment]
Hi @dantswain I am not sure if this issue as been resolved or not, the documentation says max_bytes can be configured in KafkaEx, but I am not sure how to?

https://github.com/kafkaex/kafka_ex/blob/f7e8a6d858bc145fd2752b75b43eca8fc32f95bf/lib/kafka_ex/gen_consumer.ex#L48

This issue let me think it is not possible, but the documentation says it is.
Can you help me clarify the situation here ? Thanks !

**Comment by dantswain** [comment]
Hi @adrienmo, the documentation is incorrect right now.  The documentation says how it SHOULD work but this issue is to track the fact that it doesn't work as it should.

It shouldn't actually be too hard to fix this if you'd like to take it on ;)  Otherwise it'll be in our hopper to get to as soon as we can.
