### ISSUE TITLE
no way to get topic name from handle_message_set/2 function

### ISSUE THREAD

**Issue by rom8726** [kafkaex/kafka_ex#259]
In consumer group I can't get topic name for message. I implemented function handle_message_set(message_set, state) and state is nil!

**Comment by dantswain** [comment]
Hi @rom8726

I’m traveling today so won’t be able to type out anything longer for a few hours but did you set up your state in the GemConsumer init callback?  Take a look at https://hexdocs.pm/kafka_ex/KafkaEx.GenConsumer.html#module-handler-state-and-interaction - it shows the topic and partition being passed to the init callback.  You should be able to pass them along as state for the GenConsumer.
