### ISSUE TITLE
Support new consumer offset api?

### ISSUE THREAD

**Issue by jasongoodwin** [kafkaex/kafka_ex#293]
Does Kafka_ex support the new java consumer offset api instead of using the zookeeper one? It can be a lot more difficult to manage the offsets vs the other libraries we're using in different technology stacks.

**Comment by joshuawscott** [comment]
This is definitely on the list of things to do, but supporting the variations in the API required is going to require some significant changes to the codebase, so it is not done yet. 😞

**Comment by dantswain** [comment]
@jasongoodwin Can you clarify what you mean?  Exactly what is easier with other libraries?  I just want to make sure I understand your request because it helps us decide where to focus our efforts.  AFAIK the API itself is mostly unchanged, but with the newer versions of the protocol Kafka will decide to store the offsets in Kafka rather than zookeeper.  KafkaEx never directly talks to zookeeper - offset storage is always mediated by the broker.

**Comment by travcunn** [comment]
We are using this library in production and we have 2 avenues for monitoring Kafka offsets for our alerting system: 1) Check zookeeper for offsets 2) Ask Kafka for offsets

It would be nice if we only had to check Kafka for offsets in our monitoring/alerting system.

**Comment by bjhaid** [comment]
@travcunn what version of kafka are you running, FWIW kafkaex should be able to retrieve offsets from 0.8.2 kafka see the implementation here:

https://github.com/kafkaex/kafka_ex/blob/7b939a1bdbbbcae7cf7dc4dbd118d5c50da75bdc/lib/kafka_ex/server_0_p_8_p_2.ex#L82-L111

**Comment by gorenje** [comment]
FWIW, I was looking at some [python code](https://github.com/dpkp/kafka-python/blob/703f06590be2daa7e4592b3d82df6d719a6829bb/kafka/protocol/commit.py#L44-L74) and it does seem that the request (i.e. api version 0 or 1) decides where offsets are stored. From that code, it also seems that the requests are slightly different. (I'm running 0.11 and it happily accepts both locations for offsets.)

I've got the same situation as @travcunn in that all my offsets are kafka based except those generated by kafkaex :( But I can work around that, so I can still use kafkaex 👍

**Comment by bjhaid** [comment]
@gorenje we will accept PRs to include the behavior you want

**Comment by YakShavingCatHerder** [comment]
@gorenje could you provide an example of your fix for this issue? 
Currently running Kafka 1.1 and the consumer groups for all microservices running kafka_ex have no offsets. I can see from the code you linked that the `OffsetCommitRequest_v1` class is what needs to be called in my situation but I'm fuzzy on how to implement that change.

**Comment by gorenje** [comment]
@YakShavingCatHerder I'm actually using my [own branch](https://github.com/gorenje/kafka_ex/tree/use_v1_commit) and setting the use_v1_commit in the config.exs. So mix.exs includes this in the deps:

```elixir
defp deps do
  [
    ...
    {:kafka_ex,
     git: "git://github.com/gorenje/kafka_ex",
     branch: "use_v1_commit"},
    ...
  ]
end
```
and config.exs has this:
```elixir
config :kafka_ex,
  ...
  use_v1_offsets: true # commit offsets to Kafka not Zookeeper.
```

that should make it write to kafka.
