### ISSUE TITLE
ConsumerGroup and auto_offset_reset

### ISSUE THREAD

**Issue by Freyskeyd** [kafkaex/kafka_ex#294]
Hello,

I'm trying to implement a consumer that only consume new event. I tried to use `auto_offset_reset` with both `:latest` and `:earliest` but nothing worked.

Does any example exists that can help me clarify this part of the configuration?

Thank's

**Comment by joshuawscott** [comment]
`auto_offset_reset` only applies if the consumer attempts to retrieve an offset that no longer exists on the broker. If you want to start from the last offset every time you start consuming, then I don't know if you can do that using the GenConsumer API. Consumer groups are intended to ensure that you don't miss any messages.

**Comment by gerbal** [comment]
You could fetch the latest offset using [KafkaEx.latest_offset/3](https://hexdocs.pm/kafka_ex/KafkaEx.html#latest_offset/3), and pass that value in the `fetch_options` parameter.

But as Joshua said, if you don't care about guaranteeing delivery, you probably don't need to use consumer groups. [KafkaEx.fetch/3](https://hexdocs.pm/kafka_ex/KafkaEx.html#fetch/3) or [KafkaEx.stream/3](https://hexdocs.pm/kafka_ex/KafkaEx.html#stream/3) without a consumer group should consume from the last available offset.

**Comment by Freyskeyd** [comment]
Did you have an example of `fetch` or `stream` in a supervisor tree?

**Comment by joshuawscott** [comment]
Looks like you got this working, so I'm going to close this issue if that's ok. Feel free to re-open if you have further questions on this.

**Comment by Freyskeyd** [comment]
@joshuawscott It works but I think this consumer is not properly setted up.

I don't see it on topics consumers :/

I'm using kafka 1.0.1.

any idea?

**Comment by joshuawscott** [comment]
kafka_ex uses the older method of saving consumer_group offsets to zookeeper at the moment. In any case, I don't know that you would see a consumer that isn't part of a consumer group anywhere, and I don't think the implementation you posted above would have a consumer group.
