### ISSUE TITLE
Support for controlling initial offset

### ISSUE THREAD

**Issue by technomage** [kafkaex/kafka_ex#300]
We have cases where a newly starting app should read beginning with the earliest offset of a topic.  Currently there is an option to reset offset when it is out of range, but not one to force it to earliest on startup.

**Comment by joshuawscott** [comment]
Is this using the consumer group functionality, or the lower level consumers?

**Comment by IanVaughan** [comment]
I was wondering about this too.

Within a GenConsumer, one could either update the response from the `init/1`, or add a new callback, say `handle_initial_offset/1`for example, that could return `current_offset`, thus preventing the `load_offsets` from being [called via the timeout here](https://github.com/kafkaex/kafka_ex/blob/master/lib/kafka_ex/gen_consumer.ex#L553-L559), but its just an idea!

**Comment by daekano** [comment]
I am interested in such an option as well. I can't find any functions to call or callbacks to define in order to initiate replay.

**Comment by joshuawscott** [comment]
The function of a consumer group is to save the position in the topic/partition. If you want to start from beginning every time, you should not use the ConsumerGroup, or you should use a new consumer group for each new worker.
