### ISSUE TITLE
Graceful handling of :topic_not_found

### ISSUE THREAD

**Issue by technomage** [kafkaex/kafka_ex#301]
We have circumstances where a topic is deleted and recreated, it would be nice to be able to gracefully handle the :topic_not_found error in those cases.  Allowing for that in the consumer and an optional callback to ignore would be sufficient.  Let me know if this would be acceptable and I can do a pull request.

**Comment by joshuawscott** [comment]
Is this in the GenConsumer and related consumer group functionality, or is this the lower level consumer?

**Comment by IanVaughan** [comment]
I've spotted this as well, and think I might have a solution as part of https://github.com/kafkaex/kafka_ex/issues/298, in which it can be setup to retry attempting to connect to a topic until present.

**Comment by technomage** [comment]
I ended up using a module that delays the retry by monitoring the consumer rather than directly placing it in the supervisor tree.  This is working for me.
