### ISSUE TITLE
Manual committing of offsets

### ISSUE THREAD

**Issue by batasrki** [kafkaex/kafka_ex#306]
Hello,
I apologize if I have missed some aspect of documentation, but I was wondering if there is an example of how to commit offsets manually rather than using an interval.

I'm using Kafka as a backbone of a webhook delivery system. As such, I don't want to be committing an offset to Kafka before the HTTP call is completed. As a competing interest, I also don't want to be serially consuming from the partition, but would rather take a batch of messages from Kafka, parallelize, then commit the latest contiguous offset in some time period.

If there are docs showing how to commit manually, please let me know where to find them. If not, I can add some, as long as the library has the ability to allow me to do the manual commits.

Thanks,

**Comment by batasrki** [comment]
@bjhaid thanks for the pointer. When you say "disable auto-committing", you mean at the Kafka configuration level?

**Comment by bjhaid** [comment]
@batasrki I am referring to the call of `Kafkaex.fetch`

**Comment by batasrki** [comment]
@bjhaid thanks for the prompt responses, :). I will explore. Closing this issue.
