### ISSUE TITLE
unhandled timeout in GenConsumer.consume can result in consuming events multiple times

### ISSUE THREAD

**Issue by gerbal** [kafkaex/kafka_ex#309]
If `KafkaEx.fetch` in `GenConsumer.consume` returns a timeout it can cause the ConsumerGroup to recreate the GenConsumer supervision tree, but leave existing GenConsumers active and consuming events. 

This can lead to multiple consumers consuming from the same partition. 

A log of a consumer dieing on timeout

```
 [error] GenServer #PID<0.15479.0> terminating
** (MatchError) no match of right hand side value: :timeout
    (kafka_ex) lib/kafka_ex/gen_consumer.ex:605: KafkaEx.GenConsumer.consume/1
    (kafka_ex) lib/kafka_ex/gen_consumer.ex:559: KafkaEx.GenConsumer.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :timeout
State: %KafkaEx.GenConsumer.State{acked_offset: 227, auto_offset_reset: :none, commit_interval: 5000, commit_threshold: 100, committed_offset: 227, consumer_module: Stages.Consumer, consumer_state: {}, current_offset: 227, fetch_options: [auto_commit: false, worker_name: #PID<0.1548.0>], group: "consumer-group", last_commit: -576357390048, partition: 1, topic: "application", worker_name: #PID<0.15480.0>}
```

After a few timed out connections the supervision tree ends up like so:

![selection_002](https://user-images.githubusercontent.com/5278092/45519191-0c9c4700-b782-11e8-8d54-503dabdccdb8.png)

**Comment by joshuawscott** [comment]
Thanks for the report.

How are you supervising the KafkaEx.ConsumerGroup? When I start up a pretty basic application, KafkaEx.Supervisor is in the kafka_ex app, not under the same supervisor as KafkaEx.ConsumerGroup and KafkaEx.ConsumerGroup.Manager. Any possibility of sharing the application start/2 function or at least how the supervision tree is set up?

**Comment by gerbal** [comment]
Sure, this is within the context of [KaufmannEx[(/sevenmind/kaufmannex). I'm using a `:one_for_all` supervision strategy in my supervisor. the `Supervisor.init/1` looks like so:


```elixir
def init(opts \\ [strategy: :one_for_all]) do
    consumer_group_name = KaufmannEx.Config.consumer_group()
    topics = KaufmannEx.Config.default_topics()
    gen_consumer_mod = KaufmannEx.Config.gen_consumer_mod()

    consumer_group_opts = [
      gen_consumer_mod,
      consumer_group_name,
      topics,
      opts
    ]

    children = [
      %{
        id: KafkaEx,
        start: {KafkaEx, :start, [[], []]}
      },
      %{
        id: KaufmannEx.Stages.Producer,
        start: {KaufmannEx.Stages.Producer, :start_link, []}
      },
      %{
        id: KaufmannEx.Stages.Consumer,
        start: {KaufmannEx.Stages.Consumer, :start_link, []}
      },
      %{
        id: KafkaEx.ConsumerGroup,
        start: {KafkaEx.ConsumerGroup, :start_link, consumer_group_opts},
        type: :supervisor
      },
      %{
        id: KaufmannEx.Publisher.PartitionSelector,
        start: {KaufmannEx.Publisher.PartitionSelector, :start_link, []}
      }
    ]

    Supervisor.init(children, strategy: :one_for_one)
end
```

**Comment by gerbal** [comment]
Thanks!. Running KafkaEx in the supervision tree was a partial cause of this issue. The rest was buggy code on my part.

**Comment by joshuawscott** [comment]
Thanks for the update!

**Comment by DWvanGeest** [comment]
I know this is an older bug, but we're seeing similar behavior where timeouts seem to cause "zombie" consumers to stick around after a rebalance. In our case, however, we are not starting `KafkaEx` under the same supervision tree. This is how the consumer is being started:

``` elixir
defmodule OurApp do
  use Application

  def start(_type, _args) do
    Supervisor.start_link(
      [
            %{
                  id: KafkaEx.ConsumerGroup,
                  start:
                    {KafkaEx.ConsumerGroup, :start_link,
                     [OurApp.KafkaConsumer, @consumer_group, [@topic], 
                     @consumer_group_opts]},
                 shutdown: :infinity,
                 type: :supervisor
              }
      ],
      strategy: :one_for_one,
      max_restarts: 0
    )
  end
end
```

`OurApp.KafkaConsumer` has `use KafkaEx.GenConsumer`.

I verified using `:observer` that the `KafkaEx.Supervisor` is under the `kafka_ex` app, not `our_app`. Are we doing something obviously wrong here? Thanks!

**Comment by joshuawscott** [comment]
@DWvanGeest perhaps you could open a new issue on this? Can you provide your consumer_group_opts there?

**Comment by MichaelViveros** [comment]
Hi @joshuawscott, I'm taking over for David and submitted a new issue for this, https://github.com/kafkaex/kafka_ex/issues/401.
