### ISSUE TITLE
Offset not being visibile on broker

### ISSUE THREAD

**Issue by IanVaughan** [kafkaex/kafka_ex#311]
Using LensesUI, we noticed that the Offset for the KafkaEx consumer was not being shown, when it is for other client consumers.

But, I believe it to be working ok, as in, I can kill the consumer app, keep publishing messages externally, and when the consumer boots back up, it seems to pick up from where it was last.

### Lenses UI

KafkaEx consumer never shows an Offset, even though its processed all the messages that have been published
<img width="1722" alt="screen shot 2018-09-20 at 11 39 55" src="https://user-images.githubusercontent.com/158600/45813511-b6bc2780-bcca-11e8-9654-eaa32021e2d5.png">

Other consumer, shows offset ok
<img width="1718" alt="screen shot 2018-09-20 at 11 39 37" src="https://user-images.githubusercontent.com/158600/45813509-b6bc2780-bcca-11e8-9c96-0e0eb66ac823.png">

We can inspect this directly to double check via `kafka-consumer-groups` from within the docker image: `landoop/kafka-lenses-dev:latest`

KafkaEx consumer just returns nothing, bit odd, but sorta matches.
```
root@fast-data-dev / $ kafka-consumer-groups --bootstrap-server localhost:9092 --group tracking_locations --describe
Note: This will not show information about old Zookeeper-based consumers.
```
Other consumer returns an offset, matches the UI
```
Note: This will not show information about old Zookeeper-based consumers.

TOPIC                       PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
full_payload                0          1012            1012            0               rdkafka-2ff99b8b-54eb-4867-a6f1-86f4a1dedee8 /10.0.36.140    rdkafka
```

### Code

Our Consumer
```elixir
use KafkaEx.GenConsumer

def handle_message_set(message_set, state) do
   # process messages
  {:async_commit, state}
end
```
`config/config.exs`
```elixir
config :kafka_ex,
  consumer_group: :no_consumer_group,
  disable_default_worker: true,
  sync_timeout: 3000,
  max_restarts: 10,
  max_seconds: 60,
  commit_interval: 5_000,
  commit_threshold: 100,
  use_ssl: false,
  kafka_version: "1.1.0"
```

The consumer is also started with these options :
```elixir
consumer_group_opts, do: [
    heartbeat_interval: 1_000,
    commit_interval: 1_000,
```

On localhost in dev mode, I can see these logs
```
11:49:34.395 [debug] Committed offset topic.tracking_locations/0@22 for tracking_locations
```
But alas, does not show the committed offset on any Kafka host.

Any feedback/comments/advice/help much applicated.

**Comment by joshuawscott** [comment]
Related to: https://github.com/kafkaex/kafka_ex/issues/293 

PRs are welcome to make the Kafka-based offset storage a reality, unfortunately I have not had time to tackle this yet.

**Comment by IanVaughan** [comment]
I tried that out, slight tweak to the zookeeper host, and it wasn't happy :-/
```
root@fast-data-dev / $ kafka-consumer-groups --zookeeper localhost:2181 --group tracking_locations --describe
Note: This will only show information about consumers that use ZooKeeper (not those using the Java consumer API).
Error: Executing consumer group command failed due to org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /consumers/tracking_locations/ids
```
But was intresting non the less.

> PRs are welcome to make the Kafka-based offset storage a reality, unfortunately I have not had time to tackle this yet.

Of course, thats completly fine, I was more registering an issue and hoping it was something I had wrong, but as you have linked, I now see the issue, and this can be closed in favour of that one.

**Comment by joshuawscott** [comment]
@IanVaughan what version of kafka?
