### ISSUE TITLE
Read configuration from env after release

### ISSUE THREAD

**Issue by marinakr** [kafkaex/kafka_ex#314]
I want to use different configs for mix env. (Broker addresses)
But the main problem that release runs with env that was on build and changing KAFKA_BROKERS after release do nothing
I have environment variable 
KAFKA_BROKERS="travis:9092"
1) If I set broker in prod.exs file this way
`config :kafka_ex,
  brokers: "${KAFKA_BROKERS}"` 
I receive an error `Port not set for kafka broker ${KAFKA_BROKERS}
** (Mix) Could not start application kafka_ex: exited in: KafkaEx.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) Port not set for kafka broker ${KAFKA_BROKERS}`
2) If I set broker in config.exs file this way
`config :kafka_ex,
  brokers: {:system, "KAFKA_BROKERS"}`
I receive error `** (Mix) Could not start application kafka_ex: exited in: KafkaEx.start(:normal, [])
   ** (EXIT) an exception was raised:
       ** (FunctionClauseError) no function clause matching in KafkaEx.Config.brokers/1
           (kafka_ex) lib/kafka_ex/config.ex:51: KafkaEx.Config.brokers({:system, “KAFKA_BROKERS”})` 
So for now I use syntax `config :kafka_ex,
  brokers: System.get_env("KAFKA_BROKERS")` that use env on build, and after changing KAFKA_BROKERS and restart application application still tried to connect to broker was set on release

**Comment by gerbal** [comment]
Release configuration is a known tricky thing in Elixir.  You can [configure distillery](https://github.com/bitwalker/distillery/blob/master/docs/config/runtime.md to use a config provider and read env vars at runtime.

**Comment by joshuawscott** [comment]
You can call `System.get_env("KAFKA_BROKERS")` to retrieve configuration at runtime. See
https://github.com/kafkaex/kafka_ex/blob/master/config/config.exs#L25 for an explanation of how that works. The short version is that you will need to wrap it in a function so that it can be called at runtime.

**Comment by marinakr** [comment]
> You can call `System.get_env("KAFKA_BROKERS")` to retrieve configuration at runtime. See
> https://github.com/kafkaex/kafka_ex/blob/master/config/config.exs#L25 for an explanation of how that works. The short version is that you will need to wrap it in a function so that it can be called at runtime.

It does not works with `System.get_env` because release generated in travis with travis env, and on start it use env what was on release

**Comment by joshuawscott** [comment]
Say we need to have kafka1:9092, kafka2:9092, kafka3:9092 brokers. We set KAFKA_BROKERS environment variable like
```
KAFKA_BROKERS="kafka1:9092,kafka2:9092,kafka3:9092"
```

The configuration file should look like:
```
config :kafka_ex
  brokers: {KafkaBroker, :broker_list, []}
```

Which will call the following at runtime:
```
defmodule KafkaBroker do
  def broker_list do
    "KAFKA_BROKERS"
    |> System.get_env
    |> String.split(",")
    |> Enum.map(fn pair ->
      [host, port] = String.split(pair, ":")
      {host, port}
    end)
  end
end
```
