### ISSUE TITLE
Many reconnections

### ISSUE THREAD

**Issue by epinault** [kafkaex/kafka_ex#321]
Hi

I am using Elixir 1.7, KafkaEX  0.8.3 and I am curious why I seeing many reconnection in my log, very frequently. This is running Kubernetes/docker environment.

Here is a sample

```
[debug] Closing connection to broker 8: "10.82.3.217" on port 9092
[debug] Establishing connection to broker 8: "10.82.3.217" on port 9092
[debug] Succesfully connected to broker "10.82.3.217":9092
[debug] Closing connection to broker 8: "10.82.3.217" on port 9092
[debug] Establishing connection to broker 8: "10.82.3.217" on port 9092
[debug] Succesfully connected to broker "10.82.3.217":9092
[debug] Closing connection to broker 8: "10.82.3.217" on port 9092
[debug] Establishing connection to broker 8: "10.82.3.217" on port 9092
[debug] Succesfully connected to broker "10.82.3.217":9092
[debug] Closing connection to broker 8: "10.82.3.217" on port 9092
```

What I noticed is that it seems to be using quite a bit of CPU churning because likely of that behavior

Unfortunately looking at the code I cannot tell wether the heartbeat fails or sesssion timeout

But we are using both the default value for heartbeat and session timeout in KafkaEx, as well as the default from Kafka on the server. So I am not understanding this behavior based on those configs

**Comment by joshuawscott** [comment]
The excessive CPU usage might be the same issue as #308 
I don't recommend setting your log levels to debug in production; the way the kafka protocol works is that clients are eventually timed out, and have to re-connect. Are you consuming messages during this time, or are the consumers caught up?

**Comment by epinault** [comment]
Usually the consumers are caught up and have no work

What is weird is I looke at 308 but I don t see that on my local development box that behavior. I see the scheduler being less that 5% and no reconnect at all.  But I ll give that a try and see if that helps

**Comment by epinault** [comment]
Ok, so it definitely helped drop the CPU usage (I still need to remove the logging).

I do still see those messages but per what you are saying it seems to make sense

what is the side effect of changing the wait_time here?

**Comment by joshuawscott** [comment]
When the client attempts to get a message, but none are available, it waits for the `wait_time` milliseconds before requesting again.

**Comment by epinault** [comment]
👍 thank you for your help and prompt reply! totally make sense why get a thundering hord and CPU usage!
