### ISSUE TITLE
receiving unhandled :EXIT message due to calling Task.async from GenConsumer

### ISSUE THREAD

**Issue by jasongoodwin** [kafkaex/kafka_ex#336]
I'm seeing this error in a case that isn't that unusual or farfetched and it causes the consumer terminate in kafka_ex 0.8.2.

If you call Task.async from within the process boundary of the GenConsumer, the task will fire back the termination message. 

Use case: we receive a message from kafka, then use a registry as an event bus to broadcast the message to many processes asynchronously, then await the replies from each message. It's very surprising behaviour that the consumer crashes on receipt of the message and was, for me at least, a bit confusing as receiving that message won't crash a GenServer that does the same.

**Comment by joshuawscott** [comment]
A Default `handle_info` clause was added to the GenConsumer implementation in 0.8.3

On the latest version, this is the result:
```
  require Logger

  defmodule Consumer do
    use KafkaEx.GenConsumer

    def handle_message_set(messages, state) do
      Task.async(fn ->
        messages
        |> inspect()
        |> Logger.warn()
      end)
      {:async_commit, state}
    end
  end

```

```
08:56:46.104 [warn]  [%KafkaEx.Protocol.Fetch.Message{attributes: 0, crc: 1895020546, key: nil, offset: 3, value: "HELLO"}]

08:56:46.127 [error] KafkaNamedWorker.Consumer #PID<0.190.0> received unexpected message in handle_info/2: {#Reference<0.2802147307.2094268420.227244>, :ok}


08:56:46.127 [error] KafkaNamedWorker.Consumer #PID<0.190.0> received unexpected message in handle_info/2: {:EXIT, #PID<0.194.0>, :normal}


08:56:46.127 [error] KafkaNamedWorker.Consumer #PID<0.190.0> received unexpected message in handle_info/2: {:DOWN, #Reference<0.2802147307.2094268420.227244>, :process, #PID<0.194.0>, :normal}


08:56:51.083 [debug] Committed offset my_topic/1@4 for my_consumer_group
```
