### ISSUE TITLE
No able to use kafka_version: "0.10.1" in config

### ISSUE THREAD

**Issue by chen116** [kafkaex/kafka_ex#353]
Hi, I am using the provided config file from (https://hexdocs.pm/kafka_ex/KafkaEx.Config.html), but some how only  kafka_version: "0.8.2" will work for me, when I try "0.9.0" or "0.10.1", i got error as shown below:

======================================================
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:function_clause, [{KafkaEx.Protocol.ApiVersions, :parse_response, [nil, 0], [file: 'lib/kafka_ex/protocol/api_versions.ex', line: 62]}, {KafkaEx.Server0P10AndLater, :kafka_api_versions, 1, [file: 'lib/kafka_ex/server_0_p_10_and_later.ex', line: 178]}, {KafkaEx.Server0P10AndLater, :kafka_server_init, 1, [file: 'lib/kafka_ex/server_0_p_10_and_later.ex', line: 99]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}

======================================================

any idea what I am missing?
i am using kafka_2.12-2.1.1 as my broker,

thanks

**Comment by joshuawscott** [comment]
It looks like this would happen if it was unable to make an APIVersions request from any of the brokers. This only happens when there's a network error:
https://github.com/kafkaex/kafka_ex/blob/0.10.0/lib/kafka_ex/server.ex#L959

**Comment by chen116** [comment]
For anyone who might have this problem as well, disable the ssl option worked for me
