### ISSUE TITLE
Add Topic and Partition ID to Protocol.Fetch.Message

### ISSUE THREAD

**Issue by yogodoshi** [kafkaex/kafka_ex#358]
On the [Message struct](https://github.com/kafkaex/kafka_ex/blob/master/lib/kafka_ex/protocol/fetch.ex#L46) there is the offset field but not the topic or the partition ID. It would be very useful for me if them were there as well, here is why:

```
topic_name
|> retrieve_partitions_ids
|> create_streams(topic_name)
|> Flow.from_enumerables()
|> Flow.map(&prepare_for_partition/1)
|> Flow.partition(key: {:elem, 0}, window: periodic_window)
|> Flow.reduce(&accumulator_tuple/0, &save_kafka_message_to_ets/2)
(more Flow stuff)
|> Flow.on_trigger(&send_to_redshift/3)
|> Flow.run()
```

I have a Flow with a `KafkaEx.stream` for each partition and down the road, I don't really have a way to know from which partition each message is from, which prevents me from committing the offset.

I would think that if this information would be great to have in my scenario, it would probably also be useful to others as a Map-Reduce is probably frequently used with `KafkaEx.stream` 🤔 

If you think this change makes sense let me know and I can try opening a PR implementing it :)

**Comment by joshuawscott** [comment]
Fixed in #360
