### ISSUE TITLE
how to use KafkaEx.create_topics/2

### ISSUE THREAD

**Issue by chen116** [kafkaex/kafka_ex#363]
Hi, 
I have trouble creating kafka topics using the provided **KafkaEx.create_topics/2**, in the doc(https://hexdocs.pm/kafka_ex/KafkaEx.html#create_topics/2) it shows that the function requires **[KafkaEx.Protocol.CreateTopics.Request.t()]** , so I look into the doc for **KafkaEx.Protocol.CreateTopics** module (https://hexdocs.pm/kafka_ex/KafkaEx.Protocol.CreateTopics.html#create_request/4), in that module, i see i can create a topic request using the function **create_request(correlation_id, client_id, create_topics_request, api_version)**   , but **create_topics_request** is of type **KafkaEx.Protocol.CreateTopics.Request.t()**   ,  which make me very confused because it seems like in order to create a **KafkaEx.Protocol.CreateTopics.Reques** , I first need to provide a **KafkaEx.Protocol.CreateTopics.Reques** . Please help, thank you.

My goal is to create kafka topic, thanks

**Comment by jbruggem** [comment]
Hi Chen,

indeed, the doc is not clear enough on this. Here's a code sample, I hope it helps !

```elixir
alias KafkaEx.Protocol.CreateTopics.TopicRequest
alias KafkaEx.Protocol.CreateTopics.ConfigEntry
alias KafkaEx.Protocol.CreateTopics.Response, as: CreateTopicsResponse

request = %TopicRequest{
      topic: topic_name,
      num_partitions: num_partitions,
      replication_factor: replication_factor,
      replica_assignment: [],
      config_entries: [
        %ConfigEntry{config_name: "min.insync.replicas", config_value: "#{min_in_sync_replicas}"}
      ]
    }

%CreateTopicsResponse{topic_errors: [%{error_code: error_code}]} =
      KafkaEx.create_topics([request], worker_name: worker, timeout: request_timeout)

```

**Comment by chen116** [comment]
thanks it works!
