### ISSUE TITLE
Snappy not resolving as a dependency

### ISSUE THREAD

**Issue by dantswain** [kafkaex/kafka_ex#37]
With a new project and

```
  def application do
    [applications: [:logger, :kafka_ex]]
  end

  defp deps do
    [{:kafka_ex, "~> 0.2"}]
  end
end
```

in the `mix.exs` file, I do a `mix deps.get`, `mix deps.compile`, and `iex` fails with

```
** (Mix) Could not start application snappy: could not find application file: snappy.app
```

Inspection of `mix.lock` shows that snappy was not resolved as a dependency.

I'm not sure why this is happening - I put snappy in the KafkaEx `mix.exs`.  Manually adding snappy as a dependency to the downstream project should resolve it in an emergency, but this should be fixed :(

**Comment by bjhaid** [comment]
Asked on irc, and Eric said the project has to be an hex project for it to resolve correctly.

![screen shot 2015-09-22 at 8 14 16 pm](https://cloud.githubusercontent.com/assets/593852/10036017/962a91c2-6166-11e5-9bbb-6a35b86d0556.png)

**Comment by dantswain** [comment]
Hm.  I didn't realize that.

I guess the thing that makes the most sense is to

a) remove snappy from kafka_ex's mix.exs
b) add directions to the README about how to add it manually

I can make a PR tomorrow.

I can also try to bug the snappy maintainer to push to hex...

**Comment by mzemel** [comment]
:+1:
