### ISSUE TITLE
Possible to configure batch.size for kafka produce/ Question about lacking producer in kafka_ex

### ISSUE THREAD

**Issue by chen116** [kafkaex/kafka_ex#376]
Hi,

So I am using kafka_ex to send message to my kafka broker and I am seeing jitter in latency by looking at LogAppendTime for individual messages when the sending rate is like 100Hz. So after googling and reading the kafka doc, I am guessing maybe kafka is batching my messages so thats why I am seeing jitter. But then I see that in kafka_ex, you  produce a message to broker directly instead of creating a kafka producer first before you send a message, for example in java  (https://kafka.apache.org/10/javadoc/org/apache/kafka/clients/producer/KafkaProducer.html):

```

 Properties props = new Properties();
 props.put("bootstrap.servers", "localhost:9092");
 props.put("acks", "all");
 props.put("retries", 0);
 props.put("batch.size", 16384);
 props.put("linger.ms", 1);
 props.put("buffer.memory", 33554432);
 props.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
 props.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer");

 Producer<String, String> producer = new KafkaProducer<>(props);
 for (int i = 0; i < 100; i++)
     producer.send(new ProducerRecord<String, String>("my-topic", Integer.toString(i), Integer.toString(i)));

 producer.close(); 
```

So without creating the producer first, I am not able to configure the "batch.size" in kafka_ex.   Is there a way to set the batch.size in kafka_ex, or maybe kafka_ex is designed such that each message from produce command will be sent to kafka broker immediately and not wait for the cumulative size to reach "batch.size"?

The usage of batch.size is given here (https://kafka.apache.org/documentation/#producerconfigs)

"...The producer will attempt to batch records together into fewer requests whenever multiple records are being sent to the same partition. This helps performance on both the client and the server. This configuration controls the default batch size in bytes...."

Thank you

**Comment by dantswain** [comment]
Hi @chen116 .  KafkaEx does not implement a batching producer.  You can batch your own messages using `KafkaEx.produce/2`, though this is admittedly a little opaque since you need to construct your own `ProduceRequest`.

You could build your own producer module relatively easily using a GenServer and having it build up a ProduceRequest.  I don't think we'll be adding this functionality to KafkaEx as it is right now, but this might make a decent feature for v1 (https://github.com/kafkaex/kafka_ex/blob/master/new_api.md)

**Comment by chen116** [comment]
Hi,

Thanks for the reply, so I can safely assuming there is no batching in kafka_ex, and each call to KafkaEx.produce sends out the message immediately (which is what I need) ? 

thanks

**Comment by dantswain** [comment]
Yes*

* "Immediately" assuming we know how to route messages for that partition already - i.e., it's possible we'll have to update topic metadata first, or re-establish a dead connection.  Those things should be infrequent, though.  That is, the normal condition would be to send the message(s) immediately.  It IS possible to have more than one message in a single produce request, but if you use `KafkaEx.produce("some message", 0, "some_topic")` then it will be a single, immediate, message.

**Comment by chen116** [comment]
Ok, thank you so much for clarifying
