### ISSUE TITLE
Default partitioner does not match Java client

### ISSUE THREAD

**Issue by mjparrott** [kafkaex/kafka_ex#398]
When using KafkaEx to produce to a topic that is also produced to by an application that is using the default Java client, I noticed that the partitions that were being produced to weren't the same in KafkaEx and the Java client.

The reason appears to be how `umurmur2` compares to the Java client.

In KafkaEx, the hash is calculated like so: https://github.com/kafkaex/kafka_ex/blob/403024e2fdd5a6f3ed340b5a5eea4f9e2faf265f/lib/kafka_ex/utils/murmur.ex#L32
In the default Java client, it is calculated here: https://github.com/apache/kafka/blob/717c55be971df862c55f55d245b9997f1d6f998c/clients/src/main/java/org/apache/kafka/clients/producer/internals/DefaultPartitioner.java#L59

The difference here is in the value we use to bitwise AND the key hash and the number of partitions. In KafkaEx, it is `0xFFFFFFFF`. In the Java client, it is `0x7fffffff`.

Changing the `0xFFFFFFFF` to `0x7FFFFFFF` seems to make things match. I'm wondering if just changing the `umurmur2` method is the correct approach here? And if so, how would versioning work? Since this would affect anyone using KafkaEx's default partitioner. Happy to make a PR if we have an approach.

**Comment by mjparrott** [comment]
I've made a PR that could possibly PR, it is linked to this issue.

**Comment by jbruggem** [comment]
Good catch @mjparrott :+1:

**Comment by dantswain** [comment]
Closed by #399 thanks!
