### ISSUE TITLE
Multiple consumers working the same partition in consumer group

### ISSUE THREAD

**Issue by MichaelViveros** [kafkaex/kafka_ex#401]
Within our consumer group, we've noticed the same message being processed by multiple consumers that appear to be working the same partitions, which should never happen. 

This behaviour seems similar to https://github.com/kafkaex/kafka_ex/issues/309#issuecomment-597307779 where "zombie" consumers stick around after a rebalance but it is different since we are not starting KafkaEx under the same supervision tree as our app. It still sounds eerily similar to issue 309 though since we noticed this behaviour occurs after getting timeout errors, which must trigger rebalances. 

We think the issue might be related to us upgrading Erlang OTP from 21.3 to 22.2, similar to https://github.com/kafkaex/kafka_ex/issues/389#issuecomment-562611866, and have since downgraded back to 21.3 and seen less timeout errors and less occurrences of this issue.

We are using KafkaEx 0.10 and here's what our consumer group looks like:
```elixir
consumer_group_opts = [
    auto_offset_reset: :latest,
    fetch_options: [wait_time: 10, min_bytes: 64_000, max_bytes: 4_194_304]
]
consumer_group = %{
    id: KafkaEx.ConsumerGroup,
    start:
    {KafkaEx.ConsumerGroup, :start_link,
        [OurApp.KafkaConsumer, "our_consumer_group", ["topic1"], consumer_group_opts]},
    shutdown: :infinity,
    type: :supervisor
}
```

**Comment by robotarmy** [comment]
Hi

**Comment by robotarmy** [comment]
Hi. Just a follow up on this Issue - I'm also looking into this problem.

`  @topic "topic_name"
  @consumer_group "consumer-group-name"
  @consumer_group_opts [
    auto_offset_reset: :latest,
    # increase throughput by delivering more messages at a time
    # broker will wait up to wait_time ms in an attempt to collect min_bytes of messages
    fetch_options: [wait_time: 10, min_bytes: 64_000, max_bytes: 4_194_304],
    max_restarts: 0,
    name: __MODULE__
  ]

  def supervisor() do
    %{
      id: KafkaEx.ConsumerGroup,
      start:
        {KafkaEx.ConsumerGroup, :start_link,
         [WebhookDelivery.KafkaConsumer, @consumer_group, [@topic], @consumer_group_opts]},
      shutdown: :infinity,
      type: :supervisor
    }
  end
`

The above is our Supervisor. I've setup 3 brokers in docker with internal and external ports and zookeeper managing offsets - By dropping the broker from zookeeper i'm able to trigger partition leadership changes - these trigger local consumer restarts.

My objective is to re-create the entire supervisor when one of workers hits his not_leader_for_partition error.

It seems like the design of the simple_one_for_one supervisor inside the KafkaEx lib and inside the GenConsumer gen:server I have no way to trap the error and cause all of the ConsumerGroup workers to trigger a refresh of the metadata and refresh all partition assignments.

It appears that the KafkaEx lib can support a customized pool which I could supervise myself. 

Any ideas would help. I'm reviewing #309 for any possible insights.

**Comment by joshuawscott** [comment]
So, if a consumer dies without having committed an offset, that offset will be re-processed by a future worker. I just want to make sure that's not the issue. It's possible to avoid this, but not by using the out-of-the-box offset storage.

**Comment by joshuawscott** [comment]
@MichaelViveros That config looks correct. I have not noticed this happening, even in an environment where we are consuming over the WAN and have a lot of timeouts in Kafka 1.1. This makes me wonder if there's an issue with 0.10 perhaps.

Do you have any application logs around the time this happened?

Also, please feel free to mention me on the Elixir Slack #kafkaex channel if you don't hear back after a few days, I tend to get busy and forget to check the issues here 😰

**Comment by MichaelViveros** [comment]
@joshuawscott Here are some logs from different Kafka errors we've received. We've noticed two cases for the duplicate consumes - one where different consumers within the consumer group are consuming from the same partition and one where different consumer partition processes within the same consumer are consuming from the same partition. The latter seems to be more common as of late.

```
09:14:06.893 [][error] GenServer #PID<0.17280.557> terminating
** (CaseClauseError) no case clause matching: :not_leader_for_partition
    (kafka_ex) lib/kafka_ex/gen_consumer.ex:686: KafkaEx.GenConsumer.consume/1
    (kafka_ex) lib/kafka_ex/gen_consumer.ex:630: KafkaEx.GenConsumer.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :timeout
```

```
09:11:02.210 [][error] GenServer #PID<0.12346.560> terminating
** (MatchError) no match of right hand side value: :timeout
    (kafka_ex) lib/kafka_ex/gen_consumer.ex:678: KafkaEx.GenConsumer.consume/1
    (kafka_ex) lib/kafka_ex/gen_consumer.ex:630: KafkaEx.GenConsumer.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :timeout
09:11:02.208 [][error] Receiving data from broker <BROKER> failed with :timeout
```

```
11:53:57.791 [][error] GenServer #PID<0.13510.60> terminating
** (CaseClauseError) no case clause matching: {:error, {{:EXIT, {{:case_clause, {:error, {{:badmatch, {:error, {%RuntimeError{message: "Unable to fetch metadata from any brokers. Timeout is 1000."}, [{KafkaEx.Server0P10AndLater, :retrieve_metadata_with_version, 7, [file: 'lib/kafka_ex/server.ex', line: 729]}, {KafkaEx.Server0P10AndLater, :update_metadata, 1, [file: 'lib/kafka_ex/server.ex', line: 590]}, {KafkaEx.Server0P10AndLater, :kafka_server_init, 1, [file: 'lib/kafka_ex/server_0_p_10_and_later.ex', line: 126]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}}, [{KafkaEx.GenConsumer, :init, 1, [file: 'lib/kafka_ex/gen_consumer.ex', line: 539]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}}, [{KafkaEx.GenConsumer.Supervisor, :"-start_workers/3-fun-0-", 3, [file: 'lib/kafka_ex/gen_consumer/supervisor.ex', line: 90]}, {Enum, :"-each/2-lists^foreach/1-0-", 2, [file: 'lib/enum.ex', line: 769]}, {Enum, :each, 2, [file: 'lib/enum.ex', line: 769]}, {KafkaEx.GenConsumer.Supervisor, :start_workers, 3, [file: 'lib/kafka_ex/gen_consumer/supervisor.ex', line: 89]}, {KafkaEx.GenConsumer.Supervisor, :start_link, 4, [file: 'lib/kafka_ex/gen_consumer/supervisor.ex', line: 50]}, {:supervisor, :do_start_child_i, 3, [file: 'supervisor.erl', line: 379]}, {:supervisor, :do_start_child, 2, [file: 'supervisor.erl', line: 365]}, {:supervisor, :handle_start_child, 2, [file: 'supervisor.erl', line: 671]}]}}, {:child, :undefined, :consumer, {KafkaEx.GenConsumer.Supervisor, :start_link, [OurApp.KafkaConsumer, "our_consumer_group", [{"topic1", 41}, {"topic1", 44}, {"topic1", 11}, {"topic1", 20}, {"topic1", 55}, {"topic1", 4}, {"topic1", 52}, {"topic1", 10}, {"topic1", 60}, {"topic1", 27}, {"topic1", 57}, {"topic1", 15}, {"topic1", 24}], [auto_offset_reset: :latest, fetch_options: [wait_time: 10, min_bytes: 64000, max_bytes: 4194304]]]}, :permanent, :infinity, :supervisor, [KafkaEx.GenConsumer.Supervisor]}}}
    (kafka_ex) lib/kafka_ex/consumer_group.ex:295: KafkaEx.ConsumerGroup.start_consumer/5
    (kafka_ex) lib/kafka_ex/consumer_group/manager.ex:390: KafkaEx.ConsumerGroup.Manager.start_consumer/2
    (kafka_ex) lib/kafka_ex/consumer_group/manager.ex:168: KafkaEx.ConsumerGroup.Manager.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :timeout
```

**Comment by joshuawscott** [comment]
It looks like you're running version 0.10.0 - can you see if `master` still has the same problems? There are several fixes in master that haven't been released yet:
https://github.com/kafkaex/kafka_ex/compare/0.10.0...master#diff-054499be3aaf506260a04d188f334e26R208-R215
Adds the following to gen_consumer.ex:
```
  # If the heartbeat gets an unrecoverable error.
  def handle_info(
        {:EXIT, _heartbeat_timer, {:shutdown, {:error, reason}}},
        %State{} = state
      ) do
    {:stop, {:shutdown, {:error, reason}}, state}
  end
```

https://github.com/kafkaex/kafka_ex/compare/0.10.0...master#diff-054499be3aaf506260a04d188f334e26R208-R215
Changes the terminate callback from a no-op to:
```
  def terminate(_reason, %State{generation_id: nil, member_id: nil} = state) do
    Process.unlink(state.worker_name)
    KafkaEx.stop_worker(state.worker_name)
  end
```

**Comment by MichaelViveros** [comment]
That's great to hear! We implemented another work-around already though but we are considering doing this as well, I will keep you posted. If you don't hear back from me in a week, feel free to close this issue.

**Comment by robotarmy** [comment]
I evaluated the new master patches and they do seem to behave well - I'm triggering client errors by removing and replacing /brokers/ids in ZK - that and brining up and down nodes in the cluster - the new heartbeat error handling and the terminate block seems to help - It is much harder to try to get the not_leader_for_partition error triggering.

@joshuawscott Would it be possible to cut a tag 0.10.1? for the changes on master

**Comment by joshuawscott** [comment]
@dantswain any issues with releasing master?

**Comment by joshuawscott** [comment]
I'm going to attempt to cut 0.11 soon.

**Comment by joshuawscott** [comment]
@MichaelViveros 0.11 is released, so I'm going to close this issue per what you said. Feel free to re-open if this is still an issue on 0.11
