### ISSUE TITLE
Wrong contract for KafkaEx.create_topics

### ISSUE THREAD

**Issue by VitorTrin** [kafkaex/kafka_ex#410]
The documentation says that it receives a KafkaEx.Protocol.CreateTopics.Request struct, except the only valid input is a list of KafkaEx.Protocol.CreateTopics.TopicRequest structs.

**Comment by joshuawscott** [comment]
Good catch, we'd welcome a PR to fix it.

**Comment by VitorTrin** [comment]
Should we enforce the usage of `Request` or simply change the documentation? Because as it is `Request` has no use and just sending a list is simpler. On the other hand, sending a `Request` an receiving a `Response` seems to be a design decision

**Comment by jbruggem** [comment]
I checked the code, and if I'm correct `CreateTopics.Request` is used internally to translate the request into Kafka's binary protocol. It's not meant to be used by users of KafkaEx.

So indeed, it's a question of changing the documentation.

What I don't understand is that the spec already looks correct, so I can't figure out what I'm missing.

In [kafka_ex.ex](https://github.com/kafkaex/kafka_ex/blob/master/lib/kafka_ex.ex#L685):

```elixir
# ...
# ...
# ...
alias KafkaEx.Protocol.CreateTopics.TopicRequest, as: CreateTopicsRequest
# ...
# ...
# ...
# ...
# ...
  @spec create_topics([CreateTopicsRequest.t()], Keyword.t()) ::
          CreateTopicsResponse.t()
  def create_topics(requests, opts \\ []) do
    worker_name = Keyword.get(opts, :worker_name, Config.default_worker())
    timeout = Keyword.get(opts, :timeout)
    Server.call(worker_name, {:create_topics, requests, timeout})
  end
```

**Comment by jbruggem** [comment]
The contract is correct if I generate the doc on my machine:

![image](https://user-images.githubusercontent.com/1292484/87015477-c3767c00-c1cd-11ea-95e5-fa12e33dc643.png)

On hexdocs:

![image](https://user-images.githubusercontent.com/1292484/87015540-d9843c80-c1cd-11ea-8981-fd16f84fb4cb.png)


@joshuawscott any idea what would cause the difference ?

**Comment by joshuawscott** [comment]
@jbruggem looks like it's been fixed in master already at some point. I'm going to close this; we probably do need to cut a new release, though.
