### ISSUE TITLE
Create 0.12 Release

### ISSUE THREAD

**Issue by markusfeyh** [kafkaex/kafka_ex#417]
Would it be possible to cut a new release?

**Comment by joshuawscott** [comment]
Certainly - I'll try to get this done on Monday

**Comment by lautrr** [comment]
+1

**Comment by Argonus** [comment]
@joshuawscott Can we release 0.12 ;) or something is blocking, maybe I can help somehow.

**Comment by joshuawscott** [comment]
Done! Sorry for the delay!
