### ISSUE TITLE
username and password support

### ISSUE THREAD

**Issue by pulzzedavid** [kafkaex/kafka_ex#428]
I am seeing username and password configuration for Kafka, but do not see any option for it on kafka_ex. Wondering if it is supported, and if it is, any pointer to its use would be much appreciated.

Server environment
KAFKA_CLIENT_USER=user
KAFKA_CLIENT_PASSWORD=password

**Comment by dantswain** [comment]
Hi @pulzzedavid can you provide some more details?  Kafka provides a few different security options, not all of which are currently supported in KafkaEx.  So it really depends on the details of your set up.

**Comment by pulzzedavid** [comment]
Thanks dantswain,

I am looking for username/password authentication such as described below. There are non-plain use cases as well.

https://kafka.apache.org/22/documentation.html#security_sasl_plain

**Comment by dantswain** [comment]
Ah it looks like SASL, which is a known issue, unfortunately :(  https://github.com/kafkaex/kafka_ex/issues/242

**Comment by pulzzedavid** [comment]
I see. Let me close this and track it with #242. Thanks @dantswain.
