### ISSUE TITLE
Create a new release with recent changes?

### ISSUE THREAD

**Issue by jfmyers9** [kafkaex/kafka_ex#466]
It's been quite a while since 0.12.1 was released and there seem to have been a couple of changes merged to the main branch (https://github.com/kafkaex/kafka_ex/pull/414 in particular). Is there any chance we could get a new `0.13.x` release for these changes? Longer term, what should expectations be around release cadence?

**Comment by jbruggem** [comment]
I'd be OK with that. @joshuawscott @bjhaid @dantswain WDYT ?

**Comment by bjhaid** [comment]
@jbruggem please do thanks!

**Comment by dantswain** [comment]
sounds good!
