### ISSUE TITLE
more near real time streaming

### ISSUE THREAD

**Issue by trungpham** [kafkaex/kafka_ex#48]
it seems like there is a half a second pause in between fetches.
https://github.com/kafkaex/kafka_ex/blob/master/lib/kafka_ex/server.ex#L152

maybe we can wake up the stream whenever there is a `produce` event.

**Comment by bjhaid** [comment]
> maybe we can wake up the stream whenever there is a produce event.

This is tricky as you don't know if the produce event should result in a streaming event.
