### ISSUE TITLE
Why use worker names instead of PIDs ?

### ISSUE THREAD

**Issue by ibizaman** [kafkaex/kafka_ex#50]
Hi,

First of all thank you for this great library!

I was wondering why do you require a name for kafka_workers? Why not being simply anonymous? `KafkaEx.create_worker` returns a PID after all.
This can be cumbersome for implementing a pool of workers for example. And furthermore it is considered bad practice to create a lot of atoms since they live forever in memory.

**Comment by bjhaid** [comment]
> I was wondering why do you require a name for kafka_workers? Why not being simply anonymous? KafkaEx.create_worker returns a PID after all.

This is all for convenience of the user you can easily remember an atom but not a pid, with this approach you also don't need to store the return value of `KafkaEx.create_worker`, just pass your atom in and you are fine. Also if you really need your pid afterwards you can always get it back with [Process.whereis/1](http://elixir-lang.org/docs/v1.1/elixir/Process.html#whereis/1)

> This can be cumbersome for implementing a pool of workers for example

```elixir
Enum.map(
  [:worker1, :worker2, :worker3], fn(worker) -> 
    {:ok, pid} = KafkaEx.create_worker(worker)
    pid
  end
)
```

The above will generate a list of 3 pids(workers) that you can use in a pool, depending on what pooling library you are using you might need to do more work, if it's [pg2](http://erlang.org/doc/man/pg2.html), the above should just be fine, with poolboy you might need to write a wrapper gen_server around the [KafkaEx.Server](https://github.com/kafkaex/kafka_ex/blob/master/lib/kafka_ex/server.ex).


> And furthermore it is considered bad practice to create a lot of atoms since they live forever in memory.

We are creating only a few atoms here, it becomes a problem when you are dynamically generating millions of atoms.

**Comment by ibizaman** [comment]
All valid points, thanks!

By curiosity, would you be okay with allowing a `nil` value for `worker_name` and then not registering the name ?

**Comment by bjhaid** [comment]
> By curiosity, would you be okay with allowing a nil value for worker_name and then not registering the name ?

NO, the atom is passed to `GenServer` which does the registration of the worker.

What problem are you trying to solve, maybe I can help clarify the approach

**Comment by ibizaman** [comment]
Yes sorry about that, our conversation looks like the typical X - Y problem.

My first problem is that I wanted to be able to dynamically connect and disconnect to a kafka host. By dynamically, I mean the connection is not part of the supervision tree initialization stage. I need this because my final app can be started without connecting to kafka.

For that, I replaced the stock KafkaEx Supervisor with a custom one with a simple_one_to_one strategy. I added another GenServer whose purpose is to call that supervisor's start_child function and to forward calls to the KafkaEx GenServer, if it has an active connection of course.
In graphical format:

```
Supervisor : one_to_one
├── GenServer wrapper with connect and disconnect methods
└── Supervisor : simple_one_to_one
    └── KafkaEx GenServer
```

And continuing from there, I am trying to make streaming messages extremely simple by using callback functions. So the API could be something as simple as `KafkaEx.consume(server_wrapper, topic, partition, fn (message) -> do some_logic end)`. That call would create a new worker to stream from another process, like Tasks.async if I am not mistaken.

My final goal is to call a callback function when receiving a message, avoiding the need to poll the GenEvent handler like it is needed now. And thus having something like this:

``` elixir
kafka = KafkaEx.connect(broker_info)

# ...

consumer = fn (message, {topic, partition} = state) ->
    KafkaEx.produce(kafka, topic, partition, transform(message)) end
    {:ok, state}
end

consumer1 = KafkaEx.consume(kafka, "my_topic", 0, consumer, {"other_topic", 0})
consumer2 = KafkaEx.consume(kafka, "my_topic", 1, consumer, {"other_topic", 1})
consumer3 = KafkaEx.consume(kafka, "my_topic", 2, consumer, {"other_topic", 0})

#...

KafkaEx.Consumer.stop(consumer1)
KafkaEx.Consumer.stop(consumer2)
KafkaEx.Consumer.stop(consumer3)
```

**Comment by bjhaid** [comment]
> My first problem is that I wanted to be able to dynamically connect and disconnect to a kafka host. By dynamically, I mean the connection is not part of the supervision tree initialization stage. I need this because my final app can be started without connecting to kafka.

You can omit `:kafka_ex` from the list of applications to be started in `mix.exs` and manually start it with [`Appllication.start/2`](http://elixir-lang.org/docs/v1.1/elixir/Application.html#start/2) and stop it with [`Application.stop/1`](http://elixir-lang.org/docs/v1.1/elixir/Application.html#stop/1).

> I mean the connection is not part of the supervision tree initialization stage.

Omitting the connection from the supervision initialization is tricky because when underlying socket gets into a weird state you want the supervision tree to kick the process/worker that owns the connection and a new socket will be created.

> My final goal is to call a callback function when receiving a message, avoiding the need to poll the GenEvent handler like it is needed now.

You don't need to poll the `KafkaEx.stream/3`, you can treat it like every elixir stream and pass it to `Stream` or `Enum`

I think most of what you intend to do can be done by passing a custom handler that defines a [`handle_event`](http://elixir-lang.org/docs/v1.1/elixir/GenEvent.html#c:handle_event/2) callback function, this function can be passed to [`KafkaEx.stream/3`](https://github.com/kafkaex/kafka_ex/blob/master/lib/kafka_ex.ex#L247), the function gets called whenever there is a message available (this approach also prevents your code from blocking on the stream).

**Comment by bjhaid** [comment]
Below is how I will implement what you intend without a custom handler
```
consuming_fn = fn(message) ->
    KafkaEx.produce(topic, partition, transform(message))
end

Enum.each([:consumer1, :consumer2, :consumer3], &(KafkaEx.create_worker(&1))
#spawn to prevent Enum from blocking on the stream, until the stream is closed the processes below will stay forever

spawn(fn -> Enum.each(KafkaEx.stream("my_topic", 0, worker_name: :consumer1), consuming_fn) end)
spawn(fn -> Enum.each(KafkaEx.stream("my_topic", 1, worker_name: :consumer2), consuming_fn) end)
spawn(fn -> Enum.each(KafkaEx.stream("my_topic", 2, worker_name: :consumer3), consuming_fn) end)
```

With a custom Handler

```
defmodule CustomHandler0 do
  use GenEvent

  def handle_event(message, _) do
     KafkaEx.produce("my_topic", 0, transform(message))
    {:ok, []}
  end
end

defmodule CustomHandler1 do
  use GenEvent

  def handle_event(message, _) do
     KafkaEx.produce("my_topic", 1, transform(message))
    {:ok, []}
  end
end

defmodule CustomHandler2 do
  use GenEvent

  def handle_event(message, _) do
     KafkaEx.produce("my_topic", 2, transform(message))
    {:ok, []}
  end
end

Enum.each([:consumer0, :consumer1, :consumer2], &(KafkaEx.create_worker(&1))

KafkaEx.stream("my_topic", 0, worker_name: :consumer0, handler: CustomHandler0)
KafkaEx.stream("my_topic", 0, worker_name: :consumer1, handler: CustomHandler1)
KafkaEx.stream("my_topic", 0, worker_name: :consumer2, handler: CustomHandler2)
```

Maybe allowing the user to supply custom data to the stream function that is passed with the message to the handler might make this simpler., that way you can reuse the same handler.

**Comment by ibizaman** [comment]
This is great, much, much simpler than what I planned for.

> Maybe allowing the user to supply custom data to the stream function that is passed with the message to the handler might make this simpler., that way you can reuse the same handler.

In fact, this is what I wanted to do and created #52 related to that.

> Omitting the connection from the supervision initialization is tricky because when underlying socket gets into a weird state you want the supervision tree to kick the process/worker that owns the connection and a new socket will be created.

About this, would using a supervisor supervising `KakfaEx.GenServer` with `strategy: simple_one_to_one` and `restart: transient` and launching it with `start_child` do the trick? Or a similar spec but still using `start_child`?

**Comment by bjhaid** [comment]
> About this, would using a supervisor supervising KakfaEx.GenServer with strategy: simple_one_to_one and restart: transient and launching it with start_child do the trick? Or a similar spec but still using start_child?

Is there anything you intend to achieve that the current supervisor doesn't provide?

**Comment by ibizaman** [comment]
Well in fact I don't know, I was wondering what options are there to handle the socket problem you were describing.

**Comment by ibizaman** [comment]
I remember why using Application.start could not work in my case: the [start](https://github.com/kafkaex/kafka_ex/blob/master/lib/kafka_ex.ex#L272) function doesn't care about its arguments and always read configuration values from the app env. I wanted to be able to change this dynamically, or even simply have two different connections.

**Comment by bjhaid** [comment]
> Well in fact I don't know. I was wondering what options are there to handle the socket problem you were describing.

The current code solves this problem, the socket belongs to the workers and is created as part of their initialization, when the get restarted by their supervisor a new socket is correctly created.

> I remember why using Application.start could not work in my case: the start function doesn't care about its arguments and always read configuration values from the app env.

You should put a default configuration in your app env and you can always pass kafka uris and consumer_group as a second argument to `KafkaEx.create_worker/2` which will not use the configuration values from app env

e.g:

```elixir
uris = [{"localhost", 9092}, {"localhost", 9093}, {"localhost", 9094}]
KafkaEx.create_worker(:update_consumer_metadata, [uris: uris, consumer_group: "kafka_ex", consumer_group_update_interval: 100])
```

> I wanted to be able to change this dynamically, or even simply have two different connections.

Every worker you create has an independent connection, so for every new worker you create you get a new connection to kafka.

**Comment by bjhaid** [comment]
I think most of your confusion might have been made easier with simpler documentation, I might spend sometime trying to pick things from the discussion into the docs or you can PR whatever you have learnt

**Comment by ibizaman** [comment]
I'll come up with a PR (which will close this issue). Thanks for all the info!
