### ISSUE TITLE
Allow init arguments for stream handler

### ISSUE THREAD

**Issue by ibizaman** [kafkaex/kafka_ex#52]
It would be awesome if we could give custom arguments to GenEvent handlers started by calling [`stream`](https://github.com/kafkaex/kafka_ex/blob/master/lib/kafka_ex.ex#L244).

This way I could add an initial state for example, or a callback function to be called by a custom handler.

Would you accept a PR doing that ?

**Comment by bjhaid** [comment]
Send in a PR
