### ISSUE TITLE
Fetch offset

### ISSUE THREAD

**Issue by beedub** [kafkaex/kafka_ex#54]
[KafkaEx.fetch](https://github.com/kafkaex/kafka_ex/blob/master/lib/kafka_ex.ex#L148) fetches messages using the last_offset provided by the last_offset api. Kafka looks to be returning messages starting from that offset (as opposed to starting after that offset), meaning that fetches will always include the last message consumed. I would have expected that the consumer would only fetch new messages.

1. Is this the expected behavior? Do other kafka libraries do this?
1. Should my code be tracking the offsets instead?

**Comment by ibizaman** [comment]
Hi, I don't know about 1. but about 2. you could simply use `last_offset + 1` instead of tracking the offset yourself.

**Comment by bjhaid** [comment]
@beedub sorry for my late response

> Is this the expected behavior? Do other kafka libraries do this?

No we should be moving the offset by 1 (`last_offset + 1`)

> Should my code be tracking the offsets instead?

No, please send in a PR to fix this if you can or use @ibizaman suggestion as I stop gap till I can fix it.

Thanks!

**Comment by beedub** [comment]
@bjhaid working on the changes now
