### ISSUE TITLE
CI?

### ISSUE THREAD

**Issue by beedub** [kafkaex/kafka_ex#56]
Is there CI set up for this project? The github readme displays that the build is passing even though some tests are failing (in consumer group)

**Comment by bjhaid** [comment]
CI is on [travis](https://travis-ci.org/kafkaex/kafka_ex), `consumer_group` failures will require 2 runs of the spec file (because of the time kafka will require to create the group)

**Comment by bjhaid** [comment]
see [.travis.yml](https://github.com/kafkaex/kafka_ex/blob/master/.travis.yml)

**Comment by beedub** [comment]
Ah got it. Is it free to add travis ci automatic builds for pull requests? (eg. https://github.com/elixir-lang/elixir/pull/4037)

**Comment by beedub** [comment]
> will require 2 runs of the spec file

Can you elaborate? Running `mix test test/integration/consumer_group_test.exs:105` consistently fails (ie rerunning it doesn't make it pas)

**Comment by bjhaid** [comment]
>  Is it free to add travis ci automatic builds for pull requests? 

Yes it's automatically added.

> Can you elaborate? Running mix test test/integration/consumer_group_test.exs:105 consistently fails (ie rerunning it doesn't make it pass). I'm using kafka 0.8.2. Is there a particular config that I need to have set in my kafka configs?

Kafka does coordination election/setting up consumer_group after we make a request for the `consumer_group_metadata` (they are providing a better a API to create consumer_groups but this is what we have for now, there might be ways to create them from the shell tool, I have not verified), we probably need to sleep in-between when the worker is created and when we start a fetch, I did not figure out how long we should be sleeping for, but I figured running the spec a subsequent time fixes the failure. If it still fails for you, you can try using [install_kafka.sh](https://github.com/kafkaex/kafka_ex/blob/master/install_kafka.sh) to install kafka and the run the specs with the default config against it.

**Comment by beedub** [comment]
> Yes it's automatically added.

Oh, I meant in terms of having it visible in the github pr ui as a check (the green check mark or red cross)

> Kafka does coordination election/setting up consumer_group after we make a request for the consumer_group_metadata (they are providing a better a API to create consumer_groups but this is what we have for now, there might be ways to create them from the shell tool, I have not verified), we probably need to sleep in-between when the worker is created and when we start a fetch, I did not figure out how long we should be sleeping for, but I figured running the spec a subsequent time fixes the failure. If it still fails for you, you can try using install_kafka.sh to install kafka and the run the specs with the default config against it.

Ok, I'll try to see what's happening with my particular setup. Thx!
