### ISSUE TITLE
Make elixir handle kafka daemons

### ISSUE THREAD

**Issue by ibizaman** [kafkaex/kafka_ex#60]
For now testing the app means first launching 3 separate kafka daemons by hand and also cleaning up by hand. Furthermore, there is no way to tweak the ports used by the daemons. In my case, one of the port clashes with the "production" server.

I propose to make elixir setup and monitor the kafka daemons. I don't see any cons for that apart from the coding time. The pros are:
* dynamic configuration of ports in the test setup;
* automatic setup of one or multiple kafka daemons;
* having control over the lifetime of the daemon;
* being able to clean the state of the kafka server when we want to;
* and not the least - making it easy for users of the library to setup their own tests with a kafka daemon.

I already worked on that for my project - not finished yet - so I'm asking mainly if you are interested by a PR with this?

**Comment by bjhaid** [comment]
You can send in a PR and lets see how it looks.

**Comment by ibizaman** [comment]
Hi,

I have a branch working with this right now but I still get errors in the tests. Those errors are I suppose related to your comment [here](https://github.com/kafkaex/kafka_ex/issues/56#issuecomment-162022778) because by running the tests twice (and of course stopping the kafka daemons in between), different test case fail.

With this PR, the kafka daemon are started before the tests and stopped after the tests, so we cannot anymore run the tests twice.

Would you have more information on what could solve this issue? I will test by adding an arbitrary delay between the "create_worker" and "fetch" as you suggest.

**Comment by bjhaid** [comment]
I might have to see your branch to have an idea of what you are doing, but I would assume making them mix tasks should be adequate, also kafka 0.9.0 introduces some new API that should solve some of the `consumer_groups` woes

**Comment by ibizaman** [comment]
This exists, although I do not know if that can be of any help though: https://github.com/chbatey/kafka-unit.

**Comment by dantswain** [comment]
IMHO this is a lot of code to handle a task that isn't within the scope of KafkaEx.  The maintenance burden is a concern - it could, for example, lead to KafkaEx breaking on changes to the server.properties file that have nothing to do with the operation of the client itself.  Perhaps it could spin off to a new project?

**Comment by ibizaman** [comment]
Well, I switched to docker now and it offers a very nice alternative. I mean, the burden's on docker now. I use the wurstmeister/kafka image with docker-compose and it works perfectly!

**Comment by dantswain** [comment]
Cool.  Maybe this issue can be closed?

**Comment by bjhaid** [comment]
I am closing this.
