### ISSUE TITLE
Does not work correctly when a string hostname contains four sets of numbers

### ISSUE THREAD

**Issue by marten** [kafkaex/kafka_ex#63]
I'm trying to connect over an SSH tunnel, and have told my `/etc/hosts` file to resolve the configured broker host `ip-10-4-1-11` to resolve to `127.0.0.1`. However, since KafkaEx tries to parse IP addresses, this does not work, and it tries to connect to `10.4.1.11` instead (bypassing my hosts-file).

The issue seems to be [here](https://github.com/kafkaex/kafka_ex/blob/master/lib/kafka_ex/network_client.ex#L48-L52)

```
iex(1)> Regex.scan(~r/\d+/, "ip-10-4-1-11")
[["10"], ["4"], ["1"], ["11"]]
```

**Comment by bjhaid** [comment]
You are correct, thanks for reporting this, I am pushing a fix shortly

**Comment by marten** [comment]
That was quick! You're awesome!

**Comment by bjhaid** [comment]
let me know if you want me to publish a new version with this fix in it, I can get that done sometimes this weekend

**Comment by bjhaid** [comment]
New version published https://hex.pm/packages/kafka_ex/0.4.0 along with other patches that you can find at: https://github.com/kafkaex/kafka_ex/releases/tag/0.4.0
