### ISSUE TITLE
Multi-Partition Timeout

### ISSUE THREAD

**Issue by barruumrex** [kafkaex/kafka_ex#65]
We're attempting to setup a group of workers to watch all of our partitions for certain events, transform them, and dump them into rethinkdb. We're running into an issue where certain workers are timing out and not being correctly restarted by the supervisor. Are we running into a bug with the supervision strategy or are we just doing this wrong? Would appreciate your assistance when you've got the time. 

The code looks like [this](https://gist.github.com/barruumrex/d4204f44b99c1912ad60)
The failure errors look like [this](https://gist.github.com/barruumrex/5e0cbb6329fac61f1c1c)
The observer tree looks like [this](http://i.imgur.com/iQmddln.png)

**Comment by barruumrex** [comment]
Realized shortly after writing this that the workers are getting restarted correctly, it's that the stream doesn't get restarted. I assume that the correct thing to do is to setup my own application and link my processes to the kafka_ex workers. Link each process so that it dies when its associated worker dies, it also dies. When they get restarted, they re-establish the stream.

**Comment by bjhaid** [comment]
I was writing a response when you responded, :+1:  to your approach.

**Comment by barruumrex** [comment]
So we finished changing over to supervised workers that start and process the steam. Unfortunately the error that was killing the workers earlier happens a lot. We had to bump up the restart count in order to prevent kafka_ex from just bringing down the application. I plan to spend some time tomorrow digging in to figure out where that error is coming from. Hopefully we'll have a pull request soon to go along with the issue.

**Comment by bjhaid** [comment]
From the stacktrace you shared the error is happening somewhere here https://github.com/kafkaex/kafka_ex/blob/0.3.0/lib/kafka_ex/network_client.ex#L28-L46, network related I guess

**Comment by barruumrex** [comment]
Yeah. Looks like it's just timeout errors. Probably just a problem with us being on the vpm. It's solid as a rock now that I've recompiled that file with a longer default timeout. Is there a way to set the default timeout based on configuration environment? Would be nice to set the higher for dev/test and then drop it back low for prod.

**Comment by bjhaid** [comment]
You can PR making the worker spec configurable

**Comment by barruumrex** [comment]
PR is up. Let me know if there's anything else I need to do with it.

**Comment by bjhaid** [comment]
The PR is great, what you have modified is better than what I was proposing ([worker_spec](https://github.com/kafkaex/kafka_ex/blob/master/lib/kafka_ex/supervisor.ex#L13)). See my comments on the PR
