### ISSUE TITLE
Update consumer group API to support kafka 0.9.0

### ISSUE THREAD

**Issue by bjhaid** [kafkaex/kafka_ex#67]
`ConsumerMetatdataRequest` was [removed](https://cwiki.apache.org/confluence/pages/diffpages.action?originalId=61329518&pageId=61330213) from the kafka 0.9.0 API, and replaced with a better API. We need to support the new API as described at https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol

**Comment by dantswain** [comment]
@bjhaid Does this mean that kafka_ex will not work with a 0.9.0 broker?

**Comment by dantswain** [comment]
OK, I think I misread.  Our reading of the upgrade docs says that there will be no breakage - you're just suggesting that the new consumer group API be integrated into kafka_ex.

For reference for anyone else:
http://docs.confluent.io/2.0.0/upgrade.html

> Pay careful consideration to the order in which components are upgraded. Kafka is backward compatible, which means that clients from 0.8.x releases (CP 1.0.x) will work with brokers from 0.9.x releases (CP 2.0.0), but not vice-versa. This means you always need to plan upgrades such that all brokers are upgraded before clients. Clients include any application that uses Kafka producer or consumer, command line tools, Camus, Schema Registry and Rest Proxy.

**Comment by bjhaid** [comment]
@dantswain you are correct, our integration tests currently run against 0.9.0 without issues, kafka is generally backwards compatible, this issue is to support the new API introduced in 0.9.0

**Comment by dantswain** [comment]
@bjhaid Do you have any plans to work on this / have started it?  I might be able to get on it during work hours since we're pushing to get rid of Poseidon (which is no longer maintained! yay!).

**Comment by bjhaid** [comment]
Thanks for your interest, I am yet to start working on this, and as usual I will appreciate your contributions.

Thanks once again

**Comment by dantswain** [comment]
@bjhaid How would you feel about breaking this down into bite-sized chunks?  I can probably get some hours to work on this, but it's a pretty big undertaking.  I was thinking it might be more manageable if I (or anyone else) can start by implementing structs for the new protocol messages and submitting PRs for those individually.  The down side is that it would be asking you to merge into master effectively useless code (implementation of structs but no integration of them), but that doesn't seem too horrible, especially if we maybe add disclaimers that the full feature is not yet supported.  Another option would be to create a feature branch and submit PRs against that.

**Comment by bjhaid** [comment]
I can go ahead and break it into smaller feature(s), I have not worked on this for 2 reasons:

1. I did not want to work on a feature that will not be used (I put it out here to see how much interest it will attract before investing time in it).
2. The feature might introduce backwards incompatibility, we can avoid this by having different strategies for different versions of kafka but that will mean more code/work which explains my first point more.

Given you are interested, I will invest time to make smaller issues, we can put it on a branch if you think that is necessary though I don't expect anyone to use the master branch directly, my assumption is you are either using the hex package, a release tag or pointing to a sha.

**Comment by dantswain** [comment]
I am definitely interested.  We would be using it in production, eventually.

I would avoid backwards compatibility here.  This feature is fairly difficult to implement, and any half-measures will implode pretty quickly (see: Ruby's poseidon_cluster).  I think it's best to stick with implementing it on top of the official API that's available as of 0.9.0 and not provide the functionality for users who have < 0.9.0.  We should be able to get the broker's version in the metadata and assert out if this feature is requested but not supported.

If there are folks who are on < 0.9.0 and want a solution that might work but is intentionally very simplified, I have a bit of code I could share.  We're effectively "locking" partitions in zookeeper.  This lets me manually assign partitions ahead of time and minimizes the risk of accidentally duplicating assignments.  It does not attempt to dynamically reassign partitions as consumers come online/offline.  That's where "doing it right" becomes very tricky and I'd say we should stick to the official API.

I'm fine with merging to master.  I've been using SHAs off master a lot lately because I need to pull in things as I've fixed them, lol.

**Comment by bjhaid** [comment]
@dantswain I made 6 smaller issues, I will start picking them up when I have time, when you pick anyone just comment on it, so we are not stumbling on each other

**Comment by dantswain** [comment]
@bjhaid Sounds good :+1:

**Comment by cdegroot** [comment]
Question - do we have a high level design already? I will try to pick up the remaining three wire protocol tickets, still going through the new style library after the refactor. 

What I would love to see as an end result for a high level library (a bit akin to the Java lib): a single call specifying bootstrap broker, topic(s), consumer group, a function to do partition assignments if leader, and a spec for a partition worker (module, function, optional args - the worker should probably get the partition id as an extra arg). When the group is forming the custom function is called to do partition assignments, when it is formed, a supervisor is started with a worker per partition according to the spec under it; on re-balance, the supervisor is killed and setup again. That would make interacting with kafka in the "normal" case very simple.

**Comment by leifg** [comment]
What is the status on that? I would love to see a high level consumer view.

**Comment by dantswain** [comment]
Consumer group implementation was finished in #219 and is now in master.  I would like to do a couple cleanup tasks and then a release.  HUGE thanks to @dcuddeback and @cdegroot for their help in implementing this!
