### ISSUE TITLE
Support optional startup of default worker

### ISSUE THREAD

**Issue by dantswain** [kafkaex/kafka_ex#68]
In my production scenario, I need to be able to run multiple consumer groups (potentially across multiple broker clusters) from the same VM.  

I can probably accomplish this by breaking my consumer groups up and starting one via the default `:kafka_ex` worker on startup and the rest as part of my boot process.  This seems klunky, though.  Ideally I think one could optionally start the application with no worker servers running and then launch their own set of workers on demand and name them as desired.

I think this is also contributing to some of the problems I'm seeing with consumer group management.  I think the existence of the `:kafka_ex` worker by default has made it easier to miss bugs in `KafkaEx.Server` - if we set up a test case and forget to route everything through the test worker, we could find that the default worker is handling some request that we did not expect it to handle and therefore masking what should really be a test failure.

**Comment by bjhaid** [comment]
Submit a PR that makes turning off the default worker(`:kafka_ex`) configurable

**Comment by dantswain** [comment]
OK, I will.  Just wanted to make sure you were amenable to the idea.

I'm getting failing integration tests on master.  The first time I ran it there were 5, then 1, then 4... :(  Is this known?

**Comment by bjhaid** [comment]
This https://github.com/kafkaex/kafka_ex/pull/35#issuecomment-141843295 is still true, I guess they should mostly be sorted with the new Consumer Group API, but it's not completely going away since we have to support `ConsumerGroupMetadata` forever

**Comment by dantswain** [comment]
I'm seeing something different.  I get tests passing after the first try if I only run one broker, but with 3 they don't pass after one run.

I think this is because I have my test cluster set up to replicate topics (replicating the environment of our production cluster).  Probably there are async issues with writing to one broker and being told to read from another.  Without replication, required acks kind of solve the async problem because you're always reading from the same broker to which you wrote and the ack guarantees the message is already available.  With replication, that assumption fails and occasionally you're being told to read from a replica that is not yet in sync.  I'm not 100% sure on that, but it's my best guess.

So the bottom line is probably that the integration tests are good enough right now, but in the future you/we may want to modify them to work against an async environment.  It's a pain in the butt, but it can be done.

Or, at minimum, the documentation should be updated to state that the integration tests assume no replication.

**Comment by bjhaid** [comment]
This is closed by #78

**Comment by bjhaid** [comment]
@dantswain I just published a new release([0.5.0](https://github.com/kafkaex/kafka_ex/releases/tag/0.5.0)), thanks for all the work and patches
