### ISSUE TITLE
Support for Group Membership - JoinGroup

### ISSUE THREAD

**Issue by bjhaid** [kafkaex/kafka_ex#86]
Piece meal from https://github.com/kafkaex/kafka_ex/issues/67

Specification can be found at:

https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-JoinGroupRequest

**Comment by cdegroot** [comment]
I'm gonna try my hand at it today, limited time though.

**Comment by dantswain** [comment]
:+1: @cdegroot In case you haven't followed the conversation (see #67), the idea here was to split the overall task up into first implementing the individual structs and then working on the integration.

**Comment by cdegroot** [comment]
Indeed, that's what I understood. Currently puzzling (with the Java client source next to it) what to put in the request ;-)

(off-topic: boy, is that Java client inefficient compared to what we can do in Elixir)

**Comment by cdegroot** [comment]
https://github.com/kafkaex/kafka_ex/pull/98

**Comment by bjhaid** [comment]
@cdegroot next time you could append

> closes kafkaex/kafkaex#98

to the commit message and github will auto magically tie the PR to the issue, see:
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by bjhaid** [comment]
thanks for the work and effort!
